/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author OniRuls
 */
public class HistorialVentas extends javax.swing.JPanel {

    /**
     * Creates new form HistorialVentas
     */
    public HistorialVentas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        panelHistorialVentasAzul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarPanelHistorialVentas = new javax.swing.JButton();
        scrollPaneHistorialVentas = new javax.swing.JScrollPane();
        historialVentasTable = new javax.swing.JTable();
        fondoOpacoForHistorialVentasPanel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHistorialVentasAzul.setBackground(new java.awt.Color(31, 42, 56));
        panelHistorialVentasAzul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Historial De Ventas");

        btnRegresarPanelHistorialVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresarPanelHistorialVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresarPanelHistorialVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarPanelHistorialVentas.setText("Regresar");

        javax.swing.GroupLayout panelHistorialVentasAzulLayout = new javax.swing.GroupLayout(panelHistorialVentasAzul);
        panelHistorialVentasAzul.setLayout(panelHistorialVentasAzulLayout);
        panelHistorialVentasAzulLayout.setHorizontalGroup(
            panelHistorialVentasAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialVentasAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 699, Short.MAX_VALUE)
                .addComponent(btnRegresarPanelHistorialVentas)
                .addGap(17, 17, 17))
        );
        panelHistorialVentasAzulLayout.setVerticalGroup(
            panelHistorialVentasAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialVentasAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHistorialVentasAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresarPanelHistorialVentas)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelHistorialVentasAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 50));

        historialVentasTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        historialVentasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Factura", "Fecha", "Ubicación", "Total", "Método Pago", "Acciones"
            }
        ));
        scrollPaneHistorialVentas.setViewportView(historialVentasTable);

        add(scrollPaneHistorialVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1000, 500));

        fondoOpacoForHistorialVentasPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        add(fondoOpacoForHistorialVentasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarPanelHistorialVentas;
    private javax.swing.JLabel fondoOpacoForHistorialVentasPanel;
    private javax.swing.JTable historialVentasTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel panelHistorialVentasAzul;
    private javax.swing.JScrollPane scrollPaneHistorialVentas;
    // End of variables declaration//GEN-END:variables
}
