/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author eidan
 */
public class PanelVentasMesasYGlobales extends javax.swing.JPanel {

    /**
     * Creates new form PanelReportes
     */
    public PanelVentasMesasYGlobales() {
        initComponents();
    }

    public void cargarReporte() {

        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        var facturas = frame.getFacturaDAO().obtenerTodas();

        double mesa1 = 0;
        double mesa2 = 0;
        double mesa3 = 0;
        double mesa4 = 0;
        double mesa5 = 0;

        double global = 0;

        for (var f : facturas) {

            double total = f.getTotal();
            global += total;

            String mesa = f.getMesa();

            if (mesa == null) {
                continue;
            }

            if (mesa.contains("1")) {
                mesa1 += total;
            }
            if (mesa.contains("2")) {
                mesa2 += total;
            }
            if (mesa.contains("3")) {
                mesa3 += total;
            }
            if (mesa.contains("4")) {
                mesa4 += total;
            }
            if (mesa.contains("5")) {
                mesa5 += total;
            }
        }

        lblVentasTotalesMesa1.setText("₡" + mesa1);
        lblVentasTotalesMesa2.setText("₡" + mesa2);
        lblVentasTotalesMesa3.setText("₡" + mesa3);
        lblVentasTotalesMesa4.setText("₡" + mesa4);
        lblVentasTotalesMesa5.setText("₡" + mesa5);

        lblVentasTotalesGlobal.setText("₡" + global);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelFondoTotal = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        panelReporteMesa1 = new javax.swing.JPanel();
        lblTextoVentasTotalesMesa1 = new javax.swing.JLabel();
        lblVentasTotalesMesa1 = new javax.swing.JLabel();
        panelReporteMesa2 = new javax.swing.JPanel();
        lblTextoVentasTotalesMesa2 = new javax.swing.JLabel();
        lblVentasTotalesMesa2 = new javax.swing.JLabel();
        panelReporteMesa3 = new javax.swing.JPanel();
        lblTextoVentasTotalesMesa3 = new javax.swing.JLabel();
        lblVentasTotalesMesa3 = new javax.swing.JLabel();
        panelReporteMesa4 = new javax.swing.JPanel();
        lblTextoVentasTotalesMesa4 = new javax.swing.JLabel();
        lblVentasTotalesMesa4 = new javax.swing.JLabel();
        panelReporteMesa5 = new javax.swing.JPanel();
        lblTextoVentasTotalesMesa5 = new javax.swing.JLabel();
        lblVentasTotalesMesa5 = new javax.swing.JLabel();
        panelReporteMesa6 = new javax.swing.JPanel();
        lblTextoVentasTotalesGlobal = new javax.swing.JLabel();
        lblVentasTotalesGlobal = new javax.swing.JLabel();
        lblImagenFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        panelFondoTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelFondoTotal.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 130, 60));

        panelReporteMesa1.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoVentasTotalesMesa1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTextoVentasTotalesMesa1.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoVentasTotalesMesa1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoVentasTotalesMesa1.setText("Ventas totales de mesa 1:");
        lblTextoVentasTotalesMesa1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVentasTotalesMesa1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblVentasTotalesMesa1.setForeground(new java.awt.Color(0, 0, 0));
        lblVentasTotalesMesa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTotalesMesa1.setText("50000");

        javax.swing.GroupLayout panelReporteMesa1Layout = new javax.swing.GroupLayout(panelReporteMesa1);
        panelReporteMesa1.setLayout(panelReporteMesa1Layout);
        panelReporteMesa1Layout.setHorizontalGroup(
            panelReporteMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoVentasTotalesMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasTotalesMesa1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelReporteMesa1Layout.setVerticalGroup(
            panelReporteMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelReporteMesa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoVentasTotalesMesa1)
                    .addComponent(lblVentasTotalesMesa1))
                .addGap(20, 20, 20))
        );

        panelFondoTotal.add(panelReporteMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 820, 90));

        panelReporteMesa2.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoVentasTotalesMesa2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTextoVentasTotalesMesa2.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoVentasTotalesMesa2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoVentasTotalesMesa2.setText("Ventas totales de mesa 2:");
        lblTextoVentasTotalesMesa2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVentasTotalesMesa2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblVentasTotalesMesa2.setForeground(new java.awt.Color(0, 0, 0));
        lblVentasTotalesMesa2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTotalesMesa2.setText("50000");

        javax.swing.GroupLayout panelReporteMesa2Layout = new javax.swing.GroupLayout(panelReporteMesa2);
        panelReporteMesa2.setLayout(panelReporteMesa2Layout);
        panelReporteMesa2Layout.setHorizontalGroup(
            panelReporteMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoVentasTotalesMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasTotalesMesa2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelReporteMesa2Layout.setVerticalGroup(
            panelReporteMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelReporteMesa2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoVentasTotalesMesa2)
                    .addComponent(lblVentasTotalesMesa2))
                .addGap(20, 20, 20))
        );

        panelFondoTotal.add(panelReporteMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 820, 90));

        panelReporteMesa3.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoVentasTotalesMesa3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTextoVentasTotalesMesa3.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoVentasTotalesMesa3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoVentasTotalesMesa3.setText("Ventas totales de mesa 3:");
        lblTextoVentasTotalesMesa3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVentasTotalesMesa3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblVentasTotalesMesa3.setForeground(new java.awt.Color(0, 0, 0));
        lblVentasTotalesMesa3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTotalesMesa3.setText("50000");

        javax.swing.GroupLayout panelReporteMesa3Layout = new javax.swing.GroupLayout(panelReporteMesa3);
        panelReporteMesa3.setLayout(panelReporteMesa3Layout);
        panelReporteMesa3Layout.setHorizontalGroup(
            panelReporteMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoVentasTotalesMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasTotalesMesa3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelReporteMesa3Layout.setVerticalGroup(
            panelReporteMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelReporteMesa3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoVentasTotalesMesa3)
                    .addComponent(lblVentasTotalesMesa3))
                .addGap(20, 20, 20))
        );

        panelFondoTotal.add(panelReporteMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 820, 90));

        panelReporteMesa4.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoVentasTotalesMesa4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTextoVentasTotalesMesa4.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoVentasTotalesMesa4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoVentasTotalesMesa4.setText("Ventas totales de mesa 4:");
        lblTextoVentasTotalesMesa4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVentasTotalesMesa4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblVentasTotalesMesa4.setForeground(new java.awt.Color(0, 0, 0));
        lblVentasTotalesMesa4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTotalesMesa4.setText("50000");

        javax.swing.GroupLayout panelReporteMesa4Layout = new javax.swing.GroupLayout(panelReporteMesa4);
        panelReporteMesa4.setLayout(panelReporteMesa4Layout);
        panelReporteMesa4Layout.setHorizontalGroup(
            panelReporteMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoVentasTotalesMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasTotalesMesa4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelReporteMesa4Layout.setVerticalGroup(
            panelReporteMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelReporteMesa4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoVentasTotalesMesa4)
                    .addComponent(lblVentasTotalesMesa4))
                .addGap(20, 20, 20))
        );

        panelFondoTotal.add(panelReporteMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 820, 90));

        panelReporteMesa5.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoVentasTotalesMesa5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTextoVentasTotalesMesa5.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoVentasTotalesMesa5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoVentasTotalesMesa5.setText("Ventas totales de mesa 5:");
        lblTextoVentasTotalesMesa5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVentasTotalesMesa5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblVentasTotalesMesa5.setForeground(new java.awt.Color(0, 0, 0));
        lblVentasTotalesMesa5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTotalesMesa5.setText("50000");

        javax.swing.GroupLayout panelReporteMesa5Layout = new javax.swing.GroupLayout(panelReporteMesa5);
        panelReporteMesa5.setLayout(panelReporteMesa5Layout);
        panelReporteMesa5Layout.setHorizontalGroup(
            panelReporteMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoVentasTotalesMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasTotalesMesa5, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelReporteMesa5Layout.setVerticalGroup(
            panelReporteMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa5Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelReporteMesa5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoVentasTotalesMesa5)
                    .addComponent(lblVentasTotalesMesa5))
                .addGap(20, 20, 20))
        );

        panelFondoTotal.add(panelReporteMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, 820, 90));

        panelReporteMesa6.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoVentasTotalesGlobal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTextoVentasTotalesGlobal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoVentasTotalesGlobal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTextoVentasTotalesGlobal.setText("Ventas totales global:");
        lblTextoVentasTotalesGlobal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblVentasTotalesGlobal.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblVentasTotalesGlobal.setForeground(new java.awt.Color(0, 0, 0));
        lblVentasTotalesGlobal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasTotalesGlobal.setText("50000");

        javax.swing.GroupLayout panelReporteMesa6Layout = new javax.swing.GroupLayout(panelReporteMesa6);
        panelReporteMesa6.setLayout(panelReporteMesa6Layout);
        panelReporteMesa6Layout.setHorizontalGroup(
            panelReporteMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoVentasTotalesGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVentasTotalesGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelReporteMesa6Layout.setVerticalGroup(
            panelReporteMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReporteMesa6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(panelReporteMesa6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoVentasTotalesGlobal)
                    .addComponent(lblVentasTotalesGlobal))
                .addGap(20, 20, 20))
        );

        panelFondoTotal.add(panelReporteMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 630, 820, 90));

        lblImagenFondo.setBackground(new java.awt.Color(255, 255, 255));
        lblImagenFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        panelFondoTotal.add(lblImagenFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.mostrar("menu");
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lblImagenFondo;
    private javax.swing.JLabel lblTextoVentasTotalesGlobal;
    private javax.swing.JLabel lblTextoVentasTotalesMesa1;
    private javax.swing.JLabel lblTextoVentasTotalesMesa2;
    private javax.swing.JLabel lblTextoVentasTotalesMesa3;
    private javax.swing.JLabel lblTextoVentasTotalesMesa4;
    private javax.swing.JLabel lblTextoVentasTotalesMesa5;
    private javax.swing.JLabel lblVentasTotalesGlobal;
    private javax.swing.JLabel lblVentasTotalesMesa1;
    private javax.swing.JLabel lblVentasTotalesMesa2;
    private javax.swing.JLabel lblVentasTotalesMesa3;
    private javax.swing.JLabel lblVentasTotalesMesa4;
    private javax.swing.JLabel lblVentasTotalesMesa5;
    private javax.swing.JPanel panelFondoTotal;
    private javax.swing.JPanel panelReporteMesa1;
    private javax.swing.JPanel panelReporteMesa2;
    private javax.swing.JPanel panelReporteMesa3;
    private javax.swing.JPanel panelReporteMesa4;
    private javax.swing.JPanel panelReporteMesa5;
    private javax.swing.JPanel panelReporteMesa6;
    // End of variables declaration//GEN-END:variables
}
