/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import model.Descuento;
import model.Pedido;

/**
 *
 * @author eidan
 */
public class PanelFactura extends javax.swing.JPanel {

    private model.Factura facturaActual;
    private int personaDivision;
    private String mesaDivision;

    /**
     * Creates new form PanelFactura
     */
    public PanelFactura() {
        initComponents();
        tableFactura.setEnabled(false);
        textFieldCedulaDigitada.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {

                MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(PanelFactura.this);

                var pad = frame.getPanelPadNumerico();

                pad.setCampoDestino(textFieldCedulaDigitada);
                pad.setPantallaOrigen("factura");

                frame.mostrar("padNumerico");
            }
        });
        descuentoComboBox.addItem(new Descuento("Sin descuento", 0));
        descuentoComboBox.addItem(new Descuento("Promoción especial 10%", 10));
        descuentoComboBox.addItem(new Descuento("Cliente frecuente 5%", 5));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsolute = new javax.swing.JPanel();
        panelFondoAzulOscuro = new javax.swing.JPanel();
        lblTextoFacturaHeader = new javax.swing.JLabel();
        btnProcederPago = new javax.swing.JButton();
        btnVolverFactura = new javax.swing.JButton();
        panelFondoBlancoFactura = new javax.swing.JPanel();
        lblTextoCafeteriaGranDia = new javax.swing.JLabel();
        lblTextoFactura = new javax.swing.JLabel();
        lblNumeroFactura = new javax.swing.JLabel();
        lblHoraFactura = new javax.swing.JLabel();
        scrollPaneFactura = new javax.swing.JScrollPane();
        tableFactura = new javax.swing.JTable();
        lblTextSubTotal = new javax.swing.JLabel();
        lblTextIVA = new javax.swing.JLabel();
        descuentoComboBox = new javax.swing.JComboBox<>();
        lblTextTotal = new javax.swing.JLabel();
        lblPrecioSubTotal = new javax.swing.JLabel();
        lblIVAPrecio = new javax.swing.JLabel();
        lblPrecioTotal = new javax.swing.JLabel();
        lblTextoDescuento = new javax.swing.JLabel();
        lblTextoCedula = new javax.swing.JLabel();
        textFieldCedulaDigitada = new javax.swing.JTextField();
        lblFondoImg = new javax.swing.JLabel();

        panelAbsolute.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoAzulOscuro.setBackground(new java.awt.Color(31, 42, 56));

        lblTextoFacturaHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoFacturaHeader.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTextoFacturaHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoFacturaHeader.setText("Factura");

        btnProcederPago.setBackground(new java.awt.Color(0, 204, 51));
        btnProcederPago.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnProcederPago.setForeground(new java.awt.Color(255, 255, 255));
        btnProcederPago.setText("Proceder al Pago");
        btnProcederPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcederPagoActionPerformed(evt);
            }
        });

        btnVolverFactura.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolverFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverFactura.setText("Volver");
        btnVolverFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoAzulOscuroLayout = new javax.swing.GroupLayout(panelFondoAzulOscuro);
        panelFondoAzulOscuro.setLayout(panelFondoAzulOscuroLayout);
        panelFondoAzulOscuroLayout.setHorizontalGroup(
            panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoAzulOscuroLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTextoFacturaHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 377, Short.MAX_VALUE)
                .addComponent(btnProcederPago, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFondoAzulOscuroLayout.setVerticalGroup(
            panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoAzulOscuroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoFacturaHeader)
                    .addComponent(btnProcederPago, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        panelAbsolute.add(panelFondoAzulOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 80));

        panelFondoBlancoFactura.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoCafeteriaGranDia.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoCafeteriaGranDia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextoCafeteriaGranDia.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCafeteriaGranDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoCafeteriaGranDia.setText("Cafetería Gran Día");

        lblTextoFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoFactura.setText("Factura:");

        lblNumeroFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblNumeroFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroFactura.setText("#00000");

        lblHoraFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblHoraFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoraFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblHoraFactura.setText("2/20/2026, 2:10 a.m");

        tableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        scrollPaneFactura.setViewportView(tableFactura);

        lblTextSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextSubTotal.setText("SubTotal:");

        lblTextIVA.setBackground(new java.awt.Color(255, 255, 255));
        lblTextIVA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblTextIVA.setText("IVA:");

        descuentoComboBox.setBackground(new java.awt.Color(204, 204, 204));
        descuentoComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descuentoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        descuentoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descuentoComboBoxActionPerformed(evt);
            }
        });

        lblTextTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextTotal.setText("Total:");

        lblPrecioSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecioSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecioSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioSubTotal.setText("₡5000");

        lblIVAPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblIVAPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIVAPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblIVAPrecio.setText("₡650");

        lblPrecioTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPrecioTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioTotal.setText("₡5650");

        lblTextoDescuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoDescuento.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoDescuento.setText("Descuento %:");

        lblTextoCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoCedula.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCedula.setText("Cédula:");

        textFieldCedulaDigitada.setBackground(new java.awt.Color(204, 204, 204));
        textFieldCedulaDigitada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textFieldCedulaDigitada.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout panelFondoBlancoFacturaLayout = new javax.swing.GroupLayout(panelFondoBlancoFactura);
        panelFondoBlancoFactura.setLayout(panelFondoBlancoFacturaLayout);
        panelFondoBlancoFacturaLayout.setHorizontalGroup(
            panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                .addGap(346, 346, 346)
                .addComponent(lblTextoFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumeroFactura)
                .addGap(390, 390, 390))
            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(lblTextoCafeteriaGranDia))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(lblHoraFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneFactura))
                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addComponent(lblTextoCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldCedulaDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTextIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTextTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTextoDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoBlancoFacturaLayout.createSequentialGroup()
                                        .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblIVAPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblPrecioSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(descuentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(105, 105, 105))
                                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                        .addGap(113, 113, 113)
                                        .addComponent(lblPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        panelFondoBlancoFacturaLayout.setVerticalGroup(
            panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoCafeteriaGranDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoFactura)
                    .addComponent(lblNumeroFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoraFactura)
                .addGap(37, 37, 37)
                .addComponent(scrollPaneFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoCedula)
                    .addComponent(textFieldCedulaDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextSubTotal)
                    .addComponent(lblPrecioSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextIVA)
                    .addComponent(lblIVAPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descuentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextoDescuento))
                .addGap(18, 18, 18)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextTotal)
                    .addComponent(lblPrecioTotal))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelAbsolute.add(panelFondoBlancoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 870, 650));

        lblFondoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        panelAbsolute.add(lblFondoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcederPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcederPagoActionPerformed
        // TODO add your handling code here:
        if (facturaActual == null) {
            return;
        }

        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        String cedula = textFieldCedulaDigitada.getText().trim();

        var clienteController = frame.getClienteController();

        if (cedula.isBlank()) {
            facturaActual.setCedulaCliente("NO IDENTIFICADO");
        } else {
            boolean existe = clienteController.clienteExiste(cedula);
            if (!existe) {
                int opcion = JOptionPane.showConfirmDialog(
                        this,
                        "Este cliente no está registrado en el sistema.\n¿Desea añadirlo?",
                        "Cliente no encontrado",
                        JOptionPane.YES_NO_OPTION
                );

                if (opcion == JOptionPane.YES_OPTION) {
                    var panelClientes = frame.getPanelGestionarClientes();
                    panelClientes.prefillCedula(cedula);
                    panelClientes.setOrigen("factura");
                    frame.mostrar("clientes");
                    return;

                } else {
                    
                    facturaActual.setCedulaCliente("NO IDENTIFICADO");
                }

            } else {
                facturaActual.setCedulaCliente(cedula);
            }
        }
        facturaActual.setCedulaCliente(cedula);

        Descuento d = (Descuento) descuentoComboBox.getSelectedItem();

        if (d != null) {
            facturaActual.setDescuento(d.getPorcentaje());
        }

        frame.setFacturaEnProceso(facturaActual);
        frame.mostrar("seleccionPago");
    }//GEN-LAST:event_btnProcederPagoActionPerformed

    private void descuentoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descuentoComboBoxActionPerformed
        // TODO add your handling code here:
        actualizarTotales();
    }//GEN-LAST:event_descuentoComboBoxActionPerformed

    private void btnVolverFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverFacturaActionPerformed
        // TODO add your handling code here:
        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        if (personaDivision != 0) {
            frame.mostrar("dividir");
        } else {
            frame.mostrar("pedidos");
        }
    }//GEN-LAST:event_btnVolverFacturaActionPerformed

    public void setFactura(model.Factura factura) {
        this.facturaActual = factura;
        actualizarTotales();

        lblNumeroFactura.setText(factura.getNumeroFactura());

        java.time.format.DateTimeFormatter fmt
                = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        lblHoraFactura.setText(factura.getFechaHora().format(fmt));

        var modelo = (javax.swing.table.DefaultTableModel) tableFactura.getModel();
        modelo.setRowCount(0);

        for (var d : factura.getDetalles()) {

            modelo.addRow(new Object[]{
                d.getNombreProducto(),
                d.getCantidad(),
                "₡" + d.getPrecioUnitario(),
                "₡" + d.getSubtotal()
            });
        }
    }

    private void actualizarTotales() {

        if (facturaActual == null) {
            return;
        }

        Descuento d = (Descuento) descuentoComboBox.getSelectedItem();

        if (d != null) {
            facturaActual.setDescuento(d.getPorcentaje());
        }

        lblPrecioSubTotal.setText("₡" + facturaActual.getSubtotal());
        lblIVAPrecio.setText("₡" + facturaActual.getIva());
        lblPrecioTotal.setText("₡" + facturaActual.getTotal());
    }

    public void cargarPedidoDesdeDivision(Pedido pedido, String mesa, int persona) {

        this.personaDivision = persona;
        this.mesaDivision = mesa;

        cargarPedido(pedido, mesa);
    }

    public void cargarPedido(Pedido pedido, String mesa) {

        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        var service = frame.getFacturaService();

        var factura = service.crearDesdePedido(pedido, mesa);

        setFactura(factura);
    }

    public void setFacturaDesdeDivision(model.Factura factura, String mesa, int persona) {

        this.personaDivision = persona;
        this.mesaDivision = mesa;

        setFactura(factura);
    }

    public int getPersonaDivision() {
        return personaDivision;
    }

    public String getMesaDivision() {
        return mesaDivision;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcederPago;
    private javax.swing.JButton btnVolverFactura;
    private javax.swing.JComboBox<Descuento> descuentoComboBox;
    private javax.swing.JLabel lblFondoImg;
    private javax.swing.JLabel lblHoraFactura;
    private javax.swing.JLabel lblIVAPrecio;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblPrecioSubTotal;
    private javax.swing.JLabel lblPrecioTotal;
    private javax.swing.JLabel lblTextIVA;
    private javax.swing.JLabel lblTextSubTotal;
    private javax.swing.JLabel lblTextTotal;
    private javax.swing.JLabel lblTextoCafeteriaGranDia;
    private javax.swing.JLabel lblTextoCedula;
    private javax.swing.JLabel lblTextoDescuento;
    private javax.swing.JLabel lblTextoFactura;
    private javax.swing.JLabel lblTextoFacturaHeader;
    private javax.swing.JPanel panelAbsolute;
    private javax.swing.JPanel panelFondoAzulOscuro;
    private javax.swing.JPanel panelFondoBlancoFactura;
    private javax.swing.JScrollPane scrollPaneFactura;
    private javax.swing.JTable tableFactura;
    private javax.swing.JTextField textFieldCedulaDigitada;
    // End of variables declaration//GEN-END:variables
}
