/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.Descuento;
/**
 *
 * @author eidan
 */
public class PanelMostrarFacturaYaCreada extends javax.swing.JPanel {

    /**
     * Creates new form PanelFactura
     */
    public PanelMostrarFacturaYaCreada() {
        initComponents();
        tableFactura.setEnabled(false);
        descuentoComboBoxSoloMostrar.addItem(new Descuento("Sin descuento", 0));
        descuentoComboBoxSoloMostrar.addItem(new Descuento("5%", 5));
        descuentoComboBoxSoloMostrar.addItem(new Descuento("10%", 10));
        descuentoComboBoxSoloMostrar.addItem(new Descuento("15%", 15));
        descuentoComboBoxSoloMostrar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsolute = new javax.swing.JPanel();
        panelFondoAzulOscuro = new javax.swing.JPanel();
        lblTextoFacturaHeader = new javax.swing.JLabel();
        btnVolverFactura = new javax.swing.JButton();
        panelFondoBlancoFactura = new javax.swing.JPanel();
        lblTextoCafeteriaGranDia = new javax.swing.JLabel();
        lblTextoFactura = new javax.swing.JLabel();
        lblNumeroFactura = new javax.swing.JLabel();
        lblHoraFactura = new javax.swing.JLabel();
        scrollPaneFactura = new javax.swing.JScrollPane();
        tableFactura = new javax.swing.JTable();
        lblTextSubTotal = new javax.swing.JLabel();
        lblTextIVA = new javax.swing.JLabel();
        descuentoComboBoxSoloMostrar = new javax.swing.JComboBox<>();
        lblTextTotal = new javax.swing.JLabel();
        lblSubtotalDeLaFactura = new javax.swing.JLabel();
        lblIVAAplicado = new javax.swing.JLabel();
        lblTotalDeLaFactura = new javax.swing.JLabel();
        lblTextoDescuento = new javax.swing.JLabel();
        lblTextoCedulaDelPago = new javax.swing.JLabel();
        lblCedulaDelPago = new javax.swing.JLabel();
        lblTextoMontoRecibido = new javax.swing.JLabel();
        lblMontoQueSeRecibio = new javax.swing.JLabel();
        lblTextoVuelto = new javax.swing.JLabel();
        lblVueltoDado = new javax.swing.JLabel();
        lblFondoImg = new javax.swing.JLabel();

        panelAbsolute.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoAzulOscuro.setBackground(new java.awt.Color(31, 42, 56));

        lblTextoFacturaHeader.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        lblTextoFacturaHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoFacturaHeader.setText("Factura");

        btnVolverFactura.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolverFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverFactura.setText("Volver");
        btnVolverFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoAzulOscuroLayout = new javax.swing.GroupLayout(panelFondoAzulOscuro);
        panelFondoAzulOscuro.setLayout(panelFondoAzulOscuroLayout);
        panelFondoAzulOscuroLayout.setHorizontalGroup(
            panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoAzulOscuroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblTextoFacturaHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 587, Short.MAX_VALUE)
                .addComponent(btnVolverFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFondoAzulOscuroLayout.setVerticalGroup(
            panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoAzulOscuroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoFacturaHeader)
                    .addComponent(btnVolverFactura))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelAbsolute.add(panelFondoAzulOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        panelFondoBlancoFactura.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoCafeteriaGranDia.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoCafeteriaGranDia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextoCafeteriaGranDia.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCafeteriaGranDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoCafeteriaGranDia.setText("Cafetería Gran Día");

        lblTextoFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoFactura.setText("Factura:");

        lblNumeroFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblNumeroFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroFactura.setText("#00000");

        lblHoraFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblHoraFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoraFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblHoraFactura.setText("2/20/2026, 2:10 a.m");

        tableFactura.setBackground(new java.awt.Color(204, 204, 204));
        tableFactura.setForeground(new java.awt.Color(51, 51, 51));
        tableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        scrollPaneFactura.setViewportView(tableFactura);

        lblTextSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextSubTotal.setText("SubTotal:");

        lblTextIVA.setBackground(new java.awt.Color(255, 255, 255));
        lblTextIVA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblTextIVA.setText("IVA:");

        descuentoComboBoxSoloMostrar.setBackground(new java.awt.Color(204, 204, 204));
        descuentoComboBoxSoloMostrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descuentoComboBoxSoloMostrar.setForeground(new java.awt.Color(0, 0, 0));

        lblTextTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextTotal.setText("Total:");

        lblSubtotalDeLaFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblSubtotalDeLaFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtotalDeLaFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotalDeLaFactura.setText("₡5000");

        lblIVAAplicado.setBackground(new java.awt.Color(255, 255, 255));
        lblIVAAplicado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIVAAplicado.setForeground(new java.awt.Color(0, 0, 0));
        lblIVAAplicado.setText("₡650");

        lblTotalDeLaFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblTotalDeLaFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalDeLaFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalDeLaFactura.setText("₡5650");

        lblTextoDescuento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoDescuento.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoDescuento.setText("Descuento aplicado %:");

        lblTextoCedulaDelPago.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoCedulaDelPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoCedulaDelPago.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCedulaDelPago.setText("Cédula del pago:");

        lblCedulaDelPago.setBackground(new java.awt.Color(255, 255, 255));
        lblCedulaDelPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCedulaDelPago.setForeground(new java.awt.Color(0, 0, 0));
        lblCedulaDelPago.setText("604990525");

        lblTextoMontoRecibido.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTextoMontoRecibido.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoMontoRecibido.setText("Monto recibido: ");

        lblMontoQueSeRecibio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMontoQueSeRecibio.setForeground(new java.awt.Color(0, 0, 0));
        lblMontoQueSeRecibio.setText("₡6000");

        lblTextoVuelto.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTextoVuelto.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoVuelto.setText("Vuelto:");

        lblVueltoDado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVueltoDado.setForeground(new java.awt.Color(0, 0, 0));
        lblVueltoDado.setText("₡350");

        javax.swing.GroupLayout panelFondoBlancoFacturaLayout = new javax.swing.GroupLayout(panelFondoBlancoFactura);
        panelFondoBlancoFactura.setLayout(panelFondoBlancoFacturaLayout);
        panelFondoBlancoFacturaLayout.setHorizontalGroup(
            panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneFactura))
                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addComponent(lblTextoDescuento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descuentoComboBoxSoloMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextIVA)
                                    .addComponent(lblTextSubTotal)
                                    .addComponent(lblTextTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoBlancoFacturaLayout.createSequentialGroup()
                                        .addComponent(lblTotalDeLaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblIVAAplicado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoBlancoFacturaLayout.createSequentialGroup()
                                            .addComponent(lblSubtotalDeLaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(lblTextoMontoRecibido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMontoQueSeRecibio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(lblTextoVuelto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblVueltoDado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(lblHoraFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(276, 276, 276)
                                .addComponent(lblTextoCedulaDelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCedulaDelPago, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(lblTextoFactura)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(lblTextoCafeteriaGranDia, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 118, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoBlancoFacturaLayout.setVerticalGroup(
            panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextoCafeteriaGranDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoFactura)
                    .addComponent(lblNumeroFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoraFactura)
                .addGap(9, 9, 9)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoCedulaDelPago)
                    .addComponent(lblCedulaDelPago))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextSubTotal)
                    .addComponent(lblSubtotalDeLaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextIVA)
                    .addComponent(lblIVAAplicado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descuentoComboBoxSoloMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextoDescuento))
                .addGap(18, 18, 18)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextTotal)
                    .addComponent(lblTotalDeLaFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextoMontoRecibido)
                    .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTextoVuelto)
                        .addComponent(lblVueltoDado)
                        .addComponent(lblMontoQueSeRecibio)))
                .addGap(26, 26, 26))
        );

        panelAbsolute.add(panelFondoBlancoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 870, 640));

        lblFondoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        panelAbsolute.add(lblFondoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverFacturaActionPerformed
        // TODO add your handling code here:
        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.abrirHistorial();
    }//GEN-LAST:event_btnVolverFacturaActionPerformed

    public void setFactura(model.Factura factura) {

        lblNumeroFactura.setText(factura.getNumeroFactura());
        lblHoraFactura.setText(factura.getFechaHora().toString());
        lblCedulaDelPago.setText(
                factura.getCedulaCliente() == null ? "NO IDENTIFICADO" : factura.getCedulaCliente()
        );

        lblSubtotalDeLaFactura.setText("₡" + factura.getSubtotal());
        lblIVAAplicado.setText("₡" + factura.getIva());
        
        lblTotalDeLaFactura.setText("₡" + factura.getTotal());

        lblMontoQueSeRecibio.setText("₡" + factura.getMontoRecibido());
        lblVueltoDado.setText("₡" + factura.getVuelto());

        var modelo = (javax.swing.table.DefaultTableModel) tableFactura.getModel();
        modelo.setRowCount(0);

        for (var d : factura.getDetalles()) {

            modelo.addRow(new Object[]{
                d.getNombreProducto(),
                d.getCantidad(),
                "₡" + d.getPrecioUnitario(),
                "₡" + d.getSubtotal()
            });
        }
        for (int i = 0; i < descuentoComboBoxSoloMostrar.getItemCount(); i++) {

            Descuento d = descuentoComboBoxSoloMostrar.getItemAt(i);

            if (d.getPorcentaje() == factura.getDescuento()) {
                descuentoComboBoxSoloMostrar.setSelectedIndex(i);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolverFactura;
    private javax.swing.JComboBox<Descuento> descuentoComboBoxSoloMostrar;
    private javax.swing.JLabel lblCedulaDelPago;
    private javax.swing.JLabel lblFondoImg;
    private javax.swing.JLabel lblHoraFactura;
    private javax.swing.JLabel lblIVAAplicado;
    private javax.swing.JLabel lblMontoQueSeRecibio;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblSubtotalDeLaFactura;
    private javax.swing.JLabel lblTextIVA;
    private javax.swing.JLabel lblTextSubTotal;
    private javax.swing.JLabel lblTextTotal;
    private javax.swing.JLabel lblTextoCafeteriaGranDia;
    private javax.swing.JLabel lblTextoCedulaDelPago;
    private javax.swing.JLabel lblTextoDescuento;
    private javax.swing.JLabel lblTextoFactura;
    private javax.swing.JLabel lblTextoFacturaHeader;
    private javax.swing.JLabel lblTextoMontoRecibido;
    private javax.swing.JLabel lblTextoVuelto;
    private javax.swing.JLabel lblTotalDeLaFactura;
    private javax.swing.JLabel lblVueltoDado;
    private javax.swing.JPanel panelAbsolute;
    private javax.swing.JPanel panelFondoAzulOscuro;
    private javax.swing.JPanel panelFondoBlancoFactura;
    private javax.swing.JScrollPane scrollPaneFactura;
    private javax.swing.JTable tableFactura;
    // End of variables declaration//GEN-END:variables
}
