/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;

/**
 *
 * @author cchin
 */
public class PanelProducto extends javax.swing.JPanel {

    private model.Producto producto;

    /**
     * Creates new form PanelProducto
     */
    public PanelProducto() {
        initComponents();
        setPreferredSize(new java.awt.Dimension(240, 300));

        addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                agregarAlPedido();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblPrecioProducto = new javax.swing.JLabel();
        lblNombreProducto = new javax.swing.JLabel();
        lblImagenProducto = new javax.swing.JLabel();
        lblTextoStock = new javax.swing.JLabel();
        lblNumStock = new javax.swing.JLabel();
        lblTextoID = new javax.swing.JLabel();
        lblIdProducto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        panelFondo.setBackground(new java.awt.Color(204, 204, 204));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPrecioProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrecioProducto.setForeground(new java.awt.Color(31, 198, 148));
        lblPrecioProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrecioProducto.setText("₡1,500");
        panelFondo.add(lblPrecioProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 202, 120, -1));

        lblNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreProducto.setText("Café Negro");
        panelFondo.add(lblNombreProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 202, 120, -1));

        lblImagenProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagenProducto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelFondo.add(lblImagenProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 246, 190));

        lblTextoStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoStock.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoStock.setText("Stock");
        panelFondo.add(lblTextoStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 273, 120, -1));

        lblNumStock.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumStock.setForeground(new java.awt.Color(0, 0, 0));
        lblNumStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumStock.setText("5");
        panelFondo.add(lblNumStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 273, 120, -1));

        lblTextoID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoID.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextoID.setText("ID");
        panelFondo.add(lblTextoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 242, 120, -1));

        lblIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblIdProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdProducto.setText("001");
        lblIdProducto.setVerifyInputWhenFocusTarget(false);
        panelFondo.add(lblIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 242, 120, -1));
        panelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 233, 246, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setNombre(String nombre) {
        lblNombreProducto.setText(nombre);
    }

    public void setPrecio(double precio) {
        lblPrecioProducto.setText("₡" + precio);
    }

    public void setStock(int stock) {
        lblNumStock.setText(String.valueOf(stock));
    }

    public void setId(String id) {
        lblIdProducto.setText(id);
    }

    public void setImagen(String nombreArchivo) {
        java.net.URL url
                = getClass().getResource("/imagenesProductos/" + nombreArchivo);

        if (url != null) {
            lblImagenProducto.setIcon(new ImageIcon(url));
        } else {
            lblImagenProducto.setText("Sin imagen");
        }
    }

    public void setProducto(model.Producto producto) {
        this.producto = producto;
        setNombre(producto.getNombre());
        setPrecio(producto.getPrecio());
        setStock(producto.getStock());
        setId(producto.getId());
        setImagen(producto.getRutaImagen());
    }

    private void agregarAlPedido() {
        MainFrame frame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        if (frame == null) {
            return;
        }
        var panelProductos = frame.getPanelProductos();

        if (!panelProductos.isModoSeleccion()) {
            return;
        }
        var panelPedido = frame.getPanelPedido();

        panelPedido.agregarProducto(producto);

        frame.mostrar("pedidos");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIdProducto;
    private javax.swing.JLabel lblImagenProducto;
    private javax.swing.JLabel lblNombreProducto;
    private javax.swing.JLabel lblNumStock;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JLabel lblTextoID;
    private javax.swing.JLabel lblTextoStock;
    private javax.swing.JPanel panelFondo;
    // End of variables declaration//GEN-END:variables
}
