/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.util.List;
import model.Factura;
import javax.swing.table.DefaultTableModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author OniRuls
 */
public class PanelHistorialVentas extends javax.swing.JPanel {

    private List<Factura> facturasCargadas;

    /**
     * Creates new form HistorialVentas
     */
    public PanelHistorialVentas() {
        initComponents();
        historialVentasTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {

                int fila = historialVentasTable.getSelectedRow();
                int columna = historialVentasTable.getSelectedColumn();

                if (columna == 8 && fila >= 0) {

                    Factura factura = facturasCargadas.get(fila);

                    MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(PanelHistorialVentas.this);

                    frame.abrirFacturaDesdeHistorial(factura);
                }
            }
        });
        
        textFieldFacturaABuscarPorCoincidencia.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarTabla();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        panelHistorialVentasAzul = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRegresarPanelHistorialVentas = new javax.swing.JButton();
        scrollPaneHistorialVentas = new javax.swing.JScrollPane();
        historialVentasTable = new javax.swing.JTable();
        textFieldFacturaABuscarPorCoincidencia = new javax.swing.JTextField();
        fondoOpacoForHistorialVentasPanel = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTree1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHistorialVentasAzul.setBackground(new java.awt.Color(31, 42, 56));
        panelHistorialVentasAzul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historial De Ventas");

        btnRegresarPanelHistorialVentas.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresarPanelHistorialVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresarPanelHistorialVentas.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarPanelHistorialVentas.setText("Regresar");
        btnRegresarPanelHistorialVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarPanelHistorialVentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelHistorialVentasAzulLayout = new javax.swing.GroupLayout(panelHistorialVentasAzul);
        panelHistorialVentasAzul.setLayout(panelHistorialVentasAzulLayout);
        panelHistorialVentasAzulLayout.setHorizontalGroup(
            panelHistorialVentasAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialVentasAzulLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 599, Short.MAX_VALUE)
                .addComponent(btnRegresarPanelHistorialVentas)
                .addGap(17, 17, 17))
        );
        panelHistorialVentasAzulLayout.setVerticalGroup(
            panelHistorialVentasAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialVentasAzulLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelHistorialVentasAzulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarPanelHistorialVentas)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelHistorialVentasAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 50));

        historialVentasTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        historialVentasTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        historialVentasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Factura", "Fecha", "Ubicación", "Total", "Método Pago", "Recibido", "Vuelto", "Cedula", "Acciones"
            }
        ));
        scrollPaneHistorialVentas.setViewportView(historialVentasTable);

        add(scrollPaneHistorialVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 1000, 500));

        textFieldFacturaABuscarPorCoincidencia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(textFieldFacturaABuscarPorCoincidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 930, 50));

        fondoOpacoForHistorialVentasPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        add(fondoOpacoForHistorialVentasPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarPanelHistorialVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarPanelHistorialVentasActionPerformed
        // TODO add your handling code here:
        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.mostrar("reportes");
    }//GEN-LAST:event_btnRegresarPanelHistorialVentasActionPerformed

    public void cargarHistorial(List<Factura> facturas) {

        this.facturasCargadas = facturas;
        DefaultTableModel model = (DefaultTableModel) historialVentasTable.getModel();
        model.setRowCount(0);

        for (Factura f : facturas) {

            model.addRow(new Object[]{
                f.getNumeroFactura(),
                f.getFechaHora(),
                f.getMesa(),
                "₡" + f.getTotal(),
                f.getMetodoPago(),
                "₡" + f.getMontoRecibido(),
                "₡" + f.getVuelto(),
                f.getCedulaCliente(),
                "Ver"
            });
        }
        
        textFieldFacturaABuscarPorCoincidencia.setText("");
    }
    
    private void filtrarTabla() {
        String textoBusqueda = textFieldFacturaABuscarPorCoincidencia.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) historialVentasTable.getModel();
        model.setRowCount(0);
        
        if (textoBusqueda.isEmpty()) {
            for (Factura f : facturasCargadas) {
                model.addRow(new Object[]{
                    f.getNumeroFactura(),
                    f.getFechaHora(),
                    f.getMesa(),
                    "₡" + f.getTotal(),
                    f.getMetodoPago(),
                    "₡" + f.getMontoRecibido(),
                    "₡" + f.getVuelto(),
                    f.getCedulaCliente(),
                    "Ver"
                });
            }
        } else {
            for (Factura f : facturasCargadas) {
                String numeroFactura = f.getNumeroFactura().toLowerCase();
                
                if (numeroFactura.contains(textoBusqueda)) {
                    model.addRow(new Object[]{
                        f.getNumeroFactura(),
                        f.getFechaHora(),
                        f.getMesa(),
                        "₡" + f.getTotal(),
                        f.getMetodoPago(),
                        "₡" + f.getMontoRecibido(),
                        "₡" + f.getVuelto(),
                        f.getCedulaCliente(),
                        "Ver"
                    });
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarPanelHistorialVentas;
    private javax.swing.JLabel fondoOpacoForHistorialVentasPanel;
    private javax.swing.JTable historialVentasTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel panelHistorialVentasAzul;
    private javax.swing.JScrollPane scrollPaneHistorialVentas;
    private javax.swing.JTextField textFieldFacturaABuscarPorCoincidencia;
    // End of variables declaration//GEN-END:variables
}
