/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.ProductoController;
import java.util.List;

import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import model.CategoriaProducto;
import model.Producto;
import view.WrapLayout.WrapLayout;

/**
 *
 * @author eidan
 */
public class PanelProductos extends javax.swing.JPanel {

    private ProductoController controller;
    private boolean modoSeleccion = false;

    /**
     * Creates new form PanelProductos
     */
    public PanelProductos() {
        initComponents();
        panelLista.setLayout(new WrapLayout(java.awt.FlowLayout.LEFT, 15, 15));
        comboBoxFiltradoPorCategoria.addActionListener(e -> filtrarPorCategoria());

        txtBarraBusqueda.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            private void actualizar() {

                String texto = txtBarraBusqueda.getText().trim();

                if (texto.isEmpty()) {
                    MainFrame frame = (MainFrame) SwingUtilities.getWindowAncestor(PanelProductos.this);
                    frame.getProductoController().cargarProductosEnVista();
                } else {
                    buscarProducto();
                }
            }

            @Override
            public void insertUpdate(DocumentEvent e) {
                actualizar();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                actualizar();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                actualizar();
            }
        });

    }

    public void setController(ProductoController controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelFondoCentral = new javax.swing.JPanel();
        panelBusqueda = new javax.swing.JPanel();
        txtBarraBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        comboBoxFiltradoPorCategoria = new javax.swing.JComboBox<>();
        ScrollLista = new javax.swing.JScrollPane();
        panelLista = new javax.swing.JPanel();
        btnAgregarProducto = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        labelFondoImagen = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoCentral.setBackground(new java.awt.Color(255, 255, 255));

        panelBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        panelBusqueda.setLayout(new java.awt.BorderLayout());

        txtBarraBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        txtBarraBusqueda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBarraBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        txtBarraBusqueda.setToolTipText("Buscar por ID...");
        txtBarraBusqueda.setMinimumSize(new java.awt.Dimension(54, 27));
        txtBarraBusqueda.setPreferredSize(new java.awt.Dimension(54, 27));
        txtBarraBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBarraBusquedaMouseClicked(evt);
            }
        });
        txtBarraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarraBusquedaActionPerformed(evt);
            }
        });
        panelBusqueda.add(txtBarraBusqueda, java.awt.BorderLayout.CENTER);

        btnBuscar.setBackground(new java.awt.Color(204, 255, 204));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icoQuit.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panelBusqueda.add(btnBuscar, java.awt.BorderLayout.LINE_START);

        comboBoxFiltradoPorCategoria.setBackground(new java.awt.Color(255, 255, 255));
        comboBoxFiltradoPorCategoria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxFiltradoPorCategoria.setForeground(new java.awt.Color(0, 0, 0));

        ScrollLista.setBackground(new java.awt.Color(255, 255, 255));
        ScrollLista.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelLista.setBackground(new java.awt.Color(255, 255, 255));
        panelLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ScrollLista.setViewportView(panelLista);

        javax.swing.GroupLayout panelFondoCentralLayout = new javax.swing.GroupLayout(panelFondoCentral);
        panelFondoCentral.setLayout(panelFondoCentralLayout);
        panelFondoCentralLayout.setHorizontalGroup(
            panelFondoCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxFiltradoPorCategoria, 0, 156, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelFondoCentralLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(ScrollLista, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoCentralLayout.setVerticalGroup(
            panelFondoCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboBoxFiltradoPorCategoria)
                    .addComponent(panelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(ScrollLista, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(panelFondoCentral, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 62, 863, 706));

        btnAgregarProducto.setBackground(new java.awt.Color(102, 204, 0));
        btnAgregarProducto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarProducto.setText("Gestionar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 230, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icoAtras.png"))); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setIconTextGap(15);
        btnRegresar.setPreferredSize(new java.awt.Dimension(186, 42));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        labelFondoImagen.setForeground(new java.awt.Color(255, 255, 255));
        labelFondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        jPanel1.add(labelFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        txtBarraBusqueda.setText("");
        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);
        frame.getPanelAgregarProducto().limpiarFormulario();
        frame.mostrar("agregarProducto");
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        txtBarraBusqueda.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        if (modoSeleccion) {
            frame.mostrar("pedidos");
        } else {
            frame.mostrar("menu");
        }

        modoSeleccion = false;
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void txtBarraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarraBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBarraBusquedaActionPerformed

    private void txtBarraBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBarraBusquedaMouseClicked

        MainFrame frame = (MainFrame) javax.swing.SwingUtilities.getWindowAncestor(this);

        PanelPadNumerico pad = frame.getPanelPadNumerico();

        pad.setCampoDestino(txtBarraBusqueda);
        pad.setPantallaOrigen("productos");

        frame.mostrar("padNumerico");
    }//GEN-LAST:event_txtBarraBusquedaMouseClicked

    public JPanel getPanelLista() {
        return panelLista;
    }

    public void setCategorias(List<CategoriaProducto> categorias) {

        comboBoxFiltradoPorCategoria.removeAllItems();

        comboBoxFiltradoPorCategoria.addItem(null);

        for (CategoriaProducto c : categorias) {
            comboBoxFiltradoPorCategoria.addItem(c);
        }
    }

    public void refrescarLista(List<Producto> productos) {
        panelLista.removeAll();
        for (Producto p : productos) {
            System.out.println(" -> " + p);
            PanelProducto tarjeta = new PanelProducto();
            tarjeta.setProducto(p);
            panelLista.add(tarjeta);
        }
        panelLista.revalidate();
        panelLista.repaint();
    }

    public void cargarCategorias(List<CategoriaProducto> categorias) {
        comboBoxFiltradoPorCategoria.removeAllItems();
        comboBoxFiltradoPorCategoria.addItem(null); // todas
        for (CategoriaProducto c : categorias) {
            comboBoxFiltradoPorCategoria.addItem(c);
        }
    }

    private void filtrarPorCategoria() {
        
        if (controller == null) {
            return;
        }

        CategoriaProducto cat
                = (CategoriaProducto) comboBoxFiltradoPorCategoria.getSelectedItem();

        if (cat == null) {
            controller.cargarProductosEnVista();
            return;
        }

        var lista = controller.buscarPorCategoria(cat);

        controller.mostrarProductos(lista);
    }

    public void setModoSeleccion(boolean modo) {
        this.modoSeleccion = modo;
        btnAgregarProducto.setVisible(!modo);
    }

    public boolean isModoSeleccion() {
        return modoSeleccion;
    }

    public void buscarProducto() {
        String id = txtBarraBusqueda.getText().trim();
        MainFrame frame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        ProductoController controller = frame.getProductoController();
        List<Producto> resultado = controller.buscarPorIdExacto(id);
        controller.mostrarProductos(resultado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollLista;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<CategoriaProducto> comboBoxFiltradoPorCategoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelFondoImagen;
    private javax.swing.JPanel panelBusqueda;
    private javax.swing.JPanel panelFondoCentral;
    private javax.swing.JPanel panelLista;
    private javax.swing.JTextField txtBarraBusqueda;
    // End of variables declaration//GEN-END:variables
}
