/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author eidan
 */
public class PanelProductosPorFactura extends javax.swing.JPanel {

    /**
     * Creates new form PanelProductosPorFactura
     */
    public PanelProductosPorFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoTotal = new javax.swing.JPanel();
        lblCantidadProductoEnFactura = new javax.swing.JLabel();
        lblNombreProductoAsignado = new javax.swing.JLabel();
        lblPrecioTotalPorCantidadProducto = new javax.swing.JLabel();

        panelFondoTotal.setBackground(new java.awt.Color(255, 255, 255));

        lblCantidadProductoEnFactura.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblCantidadProductoEnFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidadProductoEnFactura.setText("x2");

        lblNombreProductoAsignado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNombreProductoAsignado.setForeground(new java.awt.Color(0, 0, 0));
        lblNombreProductoAsignado.setText("Café Americano");

        lblPrecioTotalPorCantidadProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecioTotalPorCantidadProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioTotalPorCantidadProducto.setText("₡3000");

        javax.swing.GroupLayout panelFondoTotalLayout = new javax.swing.GroupLayout(panelFondoTotal);
        panelFondoTotal.setLayout(panelFondoTotalLayout);
        panelFondoTotalLayout.setHorizontalGroup(
            panelFondoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCantidadProductoEnFactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreProductoAsignado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(lblPrecioTotalPorCantidadProducto)
                .addContainerGap())
        );
        panelFondoTotalLayout.setVerticalGroup(
            panelFondoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadProductoEnFactura)
                    .addComponent(lblNombreProductoAsignado)
                    .addComponent(lblPrecioTotalPorCantidadProducto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCantidadProductoEnFactura;
    private javax.swing.JLabel lblNombreProductoAsignado;
    private javax.swing.JLabel lblPrecioTotalPorCantidadProducto;
    private javax.swing.JPanel panelFondoTotal;
    // End of variables declaration//GEN-END:variables
}
