/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import model.DivisionCuenta;
import model.Producto;
import model.ProductoDAO;
import java.util.Map;

/**
 *
 * @author eidan
 */
public class PanelCuentaSeparadas extends javax.swing.JPanel {

    private int persona;
    private DivisionCuenta division;
    private ProductoDAO productoDAO = new ProductoDAO();
    private String mesa;

    /**
     * Creates new form PanelCuentaSeparadas
     */
    public PanelCuentaSeparadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblIconoPersona = new javax.swing.JLabel();
        lblPersonaNumero = new javax.swing.JLabel();
        lblTextoTotalAPagar = new javax.swing.JLabel();
        lblTotalAPagar = new javax.swing.JLabel();
        lblTextoIVA = new javax.swing.JLabel();
        lblSubtotalMasIVA = new javax.swing.JLabel();
        lblTextoSubtotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        scrollListaDeProductosEnFactura = new javax.swing.JScrollPane();
        panelListaDeProductosEnFactura = new javax.swing.JPanel();

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        lblIconoPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgPersonaIcon.png"))); // NOI18N

        lblPersonaNumero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblPersonaNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblPersonaNumero.setText("Persona 1");

        lblTextoTotalAPagar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTextoTotalAPagar.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoTotalAPagar.setText("Total a pagar:");

        lblTotalAPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalAPagar.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalAPagar.setText("₡5650");

        lblTextoIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoIVA.setText("IVA (13%) :");

        lblSubtotalMasIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotalMasIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotalMasIVA.setText("₡650");

        lblTextoSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoSubtotal.setText("Subtotal:");

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotal.setText("₡5650");

        panelListaDeProductosEnFactura.setLayout(new javax.swing.BoxLayout(panelListaDeProductosEnFactura, javax.swing.BoxLayout.Y_AXIS));
        scrollListaDeProductosEnFactura.setViewportView(panelListaDeProductosEnFactura);

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblIconoPersona)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPersonaNumero))
                            .addGroup(panelFondoLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextoTotalAPagar)
                                    .addComponent(lblTextoIVA)
                                    .addComponent(lblTextoSubtotal))
                                .addGap(96, 96, 96)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSubtotalMasIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(scrollListaDeProductosEnFactura, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoPersona))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblPersonaNumero)))
                .addGap(18, 18, 18)
                .addComponent(scrollListaDeProductosEnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoSubtotal)
                    .addComponent(lblSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoIVA)
                    .addComponent(lblSubtotalMasIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextoTotalAPagar)
                    .addComponent(lblTotalAPagar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setPersonaNumero(String texto) {
        lblPersonaNumero.setText(texto);
    }

    public void configurar(int persona, DivisionCuenta division) {

        this.persona = persona;
        this.division = division;

        setPersonaNumero("Persona " + persona);

        actualizarVista();
    }

    public void actualizarVista() {

        if (division == null) {
            return;
        }

        panelListaDeProductosEnFactura.removeAll();

        double subtotal = 0;

        Map<String, Integer> productos = division.getProductosPersona(persona);

        if (productos == null || productos.isEmpty()) {

            lblSubtotal.setText("₡0");
            lblSubtotalMasIVA.setText("₡0");
            lblTotalAPagar.setText("₡0");

            panelListaDeProductosEnFactura.revalidate();
            panelListaDeProductosEnFactura.repaint();

        } else {

            for (var entry : productos.entrySet()) {

                String productoId = entry.getKey();
                int cantidad = entry.getValue();

                Producto p = productoDAO.buscarPorId(productoId);
                if (p == null) {
                    continue;
                }

                double totalLinea = p.getPrecio() * cantidad;
                subtotal += totalLinea;

                PanelProductosPorFactura panel = new PanelProductosPorFactura();
                panel.configurar(p.getNombre(), cantidad, totalLinea);

                panelListaDeProductosEnFactura.add(panel);
            }

            double iva = subtotal * 0.13;
            double total = subtotal + iva;

            lblSubtotal.setText("₡" + Math.round(subtotal));
            lblSubtotalMasIVA.setText("₡" + Math.round(iva));
            lblTotalAPagar.setText("₡" + Math.round(total));

            panelListaDeProductosEnFactura.revalidate();
            panelListaDeProductosEnFactura.repaint();

        }

    }

    public void setDivision(DivisionCuenta division, String mesa) {
        this.division = division;
        this.mesa = mesa;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIconoPersona;
    private javax.swing.JLabel lblPersonaNumero;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalMasIVA;
    private javax.swing.JLabel lblTextoIVA;
    private javax.swing.JLabel lblTextoSubtotal;
    private javax.swing.JLabel lblTextoTotalAPagar;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelListaDeProductosEnFactura;
    private javax.swing.JScrollPane scrollListaDeProductosEnFactura;
    // End of variables declaration//GEN-END:variables
}
