/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author eidan
 */
public class PanelDistribucionDeProductos extends javax.swing.JPanel {

    /**
     * Creates new form PanelDistribucionDeProductos
     */
    public PanelDistribucionDeProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelListaPersonas = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblTextoProducto = new javax.swing.JLabel();
        lblTextoCategoriaDelProducto = new javax.swing.JLabel();
        lblPrecioPorProducto = new javax.swing.JLabel();
        lblTextoTotal = new javax.swing.JLabel();
        lblTotalPorAsignarDelProducto = new javax.swing.JLabel();
        lblTextoAsignadas = new javax.swing.JLabel();
        lblCantidadYaAsignada = new javax.swing.JLabel();

        panelListaPersonas.setBackground(new java.awt.Color(255, 255, 255));
        panelListaPersonas.setForeground(new java.awt.Color(255, 255, 255));
        panelListaPersonas.setLayout(new javax.swing.BoxLayout(panelListaPersonas, javax.swing.BoxLayout.Y_AXIS));

        panelHeader.setBackground(new java.awt.Color(153, 153, 153));
        panelHeader.setMaximumSize(new java.awt.Dimension(620, 32767));

        lblTextoProducto.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTextoProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoProducto.setText("Croissant");

        lblTextoCategoriaDelProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTextoCategoriaDelProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoCategoriaDelProducto.setText("Bebidas");

        lblPrecioPorProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPrecioPorProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblPrecioPorProducto.setText("₡2000");

        lblTextoTotal.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTextoTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoTotal.setText("Total:");

        lblTotalPorAsignarDelProducto.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTotalPorAsignarDelProducto.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalPorAsignarDelProducto.setText("2");

        lblTextoAsignadas.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTextoAsignadas.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoAsignadas.setText("Asignadas:");

        lblCantidadYaAsignada.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblCantidadYaAsignada.setForeground(new java.awt.Color(0, 0, 0));
        lblCantidadYaAsignada.setText("0");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(lblTextoProducto)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrecioPorProducto))
                    .addComponent(lblTextoCategoriaDelProducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(lblTextoTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPorAsignarDelProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTextoAsignadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCantidadYaAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextoProducto)
                            .addComponent(lblPrecioPorProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTextoCategoriaDelProducto))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextoTotal)
                            .addComponent(lblTotalPorAsignarDelProducto)
                            .addComponent(lblTextoAsignadas)
                            .addComponent(lblCantidadYaAsignada))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelListaPersonas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListaPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCantidadYaAsignada;
    private javax.swing.JLabel lblPrecioPorProducto;
    private javax.swing.JLabel lblTextoAsignadas;
    private javax.swing.JLabel lblTextoCategoriaDelProducto;
    private javax.swing.JLabel lblTextoProducto;
    private javax.swing.JLabel lblTextoTotal;
    private javax.swing.JLabel lblTotalPorAsignarDelProducto;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelListaPersonas;
    // End of variables declaration//GEN-END:variables
}
