/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author eidan
 */
public class PanelDividirCuenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelDividirCuenta
     */
    public PanelDividirCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoTotal = new javax.swing.JPanel();
        panelHeader = new javax.swing.JPanel();
        lblTituloDivision = new javax.swing.JLabel();
        lblTextoPedido = new javax.swing.JLabel();
        lblNumeroPedido = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        panelConfigurarBotones = new javax.swing.JPanel();
        btnMenos = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        lblNumeroDePersonasADividir = new javax.swing.JLabel();
        lblTextoPersonas = new javax.swing.JLabel();
        panelFondoDistribucion = new javax.swing.JPanel();
        scrollPaneDistribucionDeProductos = new javax.swing.JScrollPane();
        panelDistribucionDeProductos = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        scrollPaneCuentasSeparadas = new javax.swing.JScrollPane();
        panelCuentasSeparadas = new javax.swing.JPanel();
        panelResumenGeneral = new javax.swing.JPanel();
        lblTextoResumenGeneral = new javax.swing.JLabel();
        lblTextoTotalOriginal = new javax.swing.JLabel();
        lblTextoTotalAsignado = new javax.swing.JLabel();
        lblTextoPendienteAsignar = new javax.swing.JLabel();
        lblTextoUnidadesPendientes = new javax.swing.JLabel();
        lblTotalOriginal = new javax.swing.JLabel();
        lblTotalAsignado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUnidadesPendientes = new javax.swing.JLabel();
        lblFondoImagen = new javax.swing.JLabel();

        panelFondoTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHeader.setBackground(new java.awt.Color(31, 42, 56));

        lblTituloDivision.setFont(new java.awt.Font("Segoe UI Black", 0, 21)); // NOI18N
        lblTituloDivision.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloDivision.setText("Dividir cuenta - Mesa 2");

        lblTextoPedido.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoPedido.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        lblTextoPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoPedido.setText("Pedido:");

        lblNumeroPedido.setBackground(new java.awt.Color(102, 102, 102));
        lblNumeroPedido.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        lblNumeroPedido.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroPedido.setText("#00014");

        btnVolver.setBackground(new java.awt.Color(107, 114, 128));
        btnVolver.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setText("Regresar");

        panelConfigurarBotones.setBackground(new java.awt.Color(55, 65, 82));
        panelConfigurarBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnMenos.setBackground(new java.awt.Color(103, 127, 235));
        btnMenos.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnMenos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenos.setText("-");
        btnMenos.setPreferredSize(new java.awt.Dimension(46, 46));

        btnMas.setBackground(new java.awt.Color(103, 127, 235));
        btnMas.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        btnMas.setForeground(new java.awt.Color(255, 255, 255));
        btnMas.setText("+");
        btnMas.setPreferredSize(new java.awt.Dimension(46, 46));

        lblNumeroDePersonasADividir.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNumeroDePersonasADividir.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroDePersonasADividir.setText("1");

        javax.swing.GroupLayout panelConfigurarBotonesLayout = new javax.swing.GroupLayout(panelConfigurarBotones);
        panelConfigurarBotones.setLayout(panelConfigurarBotonesLayout);
        panelConfigurarBotonesLayout.setHorizontalGroup(
            panelConfigurarBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConfigurarBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblNumeroDePersonasADividir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelConfigurarBotonesLayout.setVerticalGroup(
            panelConfigurarBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConfigurarBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConfigurarBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMenos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNumeroDePersonasADividir))
                .addContainerGap())
        );

        lblTextoPersonas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextoPersonas.setForeground(new java.awt.Color(255, 255, 255));
        lblTextoPersonas.setText("Número de personas:");

        javax.swing.GroupLayout panelHeaderLayout = new javax.swing.GroupLayout(panelHeader);
        panelHeader.setLayout(panelHeaderLayout);
        panelHeaderLayout.setHorizontalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addComponent(lblTextoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTituloDivision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(lblTextoPersonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelConfigurarBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        panelHeaderLayout.setVerticalGroup(
            panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloDivision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoPedido)
                    .addComponent(lblNumeroPedido))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeaderLayout.createSequentialGroup()
                .addComponent(panelConfigurarBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelHeaderLayout.createSequentialGroup()
                .addGroup(panelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnVolver))
                    .addGroup(panelHeaderLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTextoPersonas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFondoTotal.add(panelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 80));

        panelFondoDistribucion.setBackground(new java.awt.Color(204, 204, 204));
        panelFondoDistribucion.setForeground(new java.awt.Color(102, 255, 255));

        scrollPaneDistribucionDeProductos.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneDistribucionDeProductos.setForeground(new java.awt.Color(255, 255, 255));
        scrollPaneDistribucionDeProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelDistribucionDeProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelDistribucionDeProductos.setForeground(new java.awt.Color(255, 255, 255));
        panelDistribucionDeProductos.setLayout(new javax.swing.BoxLayout(panelDistribucionDeProductos, javax.swing.BoxLayout.LINE_AXIS));
        scrollPaneDistribucionDeProductos.setViewportView(panelDistribucionDeProductos);

        panelFooter.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Para poder confirmar debe distribuir todos las unidades del pedido.");

        btnCancelar.setBackground(new java.awt.Color(255, 102, 102));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar división");

        btnConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmar.setText("Confirmar y crear facturas separadas");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirmar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancelar)
                        .addComponent(btnConfirmar))
                    .addComponent(jLabel2))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        scrollPaneCuentasSeparadas.setForeground(new java.awt.Color(255, 255, 255));
        scrollPaneCuentasSeparadas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        panelCuentasSeparadas.setBackground(new java.awt.Color(255, 255, 255));
        panelCuentasSeparadas.setLayout(new javax.swing.BoxLayout(panelCuentasSeparadas, javax.swing.BoxLayout.Y_AXIS));
        scrollPaneCuentasSeparadas.setViewportView(panelCuentasSeparadas);

        panelResumenGeneral.setBackground(new java.awt.Color(255, 255, 255));

        lblTextoResumenGeneral.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblTextoResumenGeneral.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoResumenGeneral.setText("Resumen general");

        lblTextoTotalOriginal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoTotalOriginal.setText("Total original:");

        lblTextoTotalAsignado.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoTotalAsignado.setText("Total asignado:");

        lblTextoPendienteAsignar.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoPendienteAsignar.setText("Pendiente asignar");

        lblTextoUnidadesPendientes.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblTextoUnidadesPendientes.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoUnidadesPendientes.setText("Unidades pendientes:");

        lblTotalOriginal.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalOriginal.setText("₡21500");

        lblTotalAsignado.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalAsignado.setText("₡0");

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("₡21500");

        lblUnidadesPendientes.setForeground(new java.awt.Color(0, 0, 0));
        lblUnidadesPendientes.setText("8");

        javax.swing.GroupLayout panelResumenGeneralLayout = new javax.swing.GroupLayout(panelResumenGeneral);
        panelResumenGeneral.setLayout(panelResumenGeneralLayout);
        panelResumenGeneralLayout.setHorizontalGroup(
            panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelResumenGeneralLayout.createSequentialGroup()
                        .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelResumenGeneralLayout.createSequentialGroup()
                                .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextoTotalOriginal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTextoTotalAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTextoUnidadesPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelResumenGeneralLayout.createSequentialGroup()
                                .addComponent(lblTextoPendienteAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(128, 128, 128)))
                        .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTotalOriginal, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(lblTotalAsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblUnidadesPendientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(panelResumenGeneralLayout.createSequentialGroup()
                        .addComponent(lblTextoResumenGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelResumenGeneralLayout.setVerticalGroup(
            panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenGeneralLayout.createSequentialGroup()
                .addComponent(lblTextoResumenGeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoTotalOriginal)
                    .addComponent(lblTotalOriginal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoTotalAsignado)
                    .addComponent(lblTotalAsignado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoPendienteAsignar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelResumenGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoUnidadesPendientes)
                    .addComponent(lblUnidadesPendientes))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoDistribucionLayout = new javax.swing.GroupLayout(panelFondoDistribucion);
        panelFondoDistribucion.setLayout(panelFondoDistribucionLayout);
        panelFondoDistribucionLayout.setHorizontalGroup(
            panelFondoDistribucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoDistribucionLayout.createSequentialGroup()
                .addComponent(scrollPaneDistribucionDeProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoDistribucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneCuentasSeparadas)
                    .addComponent(panelResumenGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoDistribucionLayout.setVerticalGroup(
            panelFondoDistribucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoDistribucionLayout.createSequentialGroup()
                .addGroup(panelFondoDistribucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneDistribucionDeProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addGroup(panelFondoDistribucionLayout.createSequentialGroup()
                        .addComponent(scrollPaneCuentasSeparadas, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelResumenGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFondoTotal.add(panelFondoDistribucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1024, 690));

        lblFondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        panelFondoTotal.add(lblFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 768, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFondoImagen;
    private javax.swing.JLabel lblNumeroDePersonasADividir;
    private javax.swing.JLabel lblNumeroPedido;
    private javax.swing.JLabel lblTextoPedido;
    private javax.swing.JLabel lblTextoPendienteAsignar;
    private javax.swing.JLabel lblTextoPersonas;
    private javax.swing.JLabel lblTextoResumenGeneral;
    private javax.swing.JLabel lblTextoTotalAsignado;
    private javax.swing.JLabel lblTextoTotalOriginal;
    private javax.swing.JLabel lblTextoUnidadesPendientes;
    private javax.swing.JLabel lblTituloDivision;
    private javax.swing.JLabel lblTotalAsignado;
    private javax.swing.JLabel lblTotalOriginal;
    private javax.swing.JLabel lblUnidadesPendientes;
    private javax.swing.JPanel panelConfigurarBotones;
    private javax.swing.JPanel panelCuentasSeparadas;
    private javax.swing.JPanel panelDistribucionDeProductos;
    private javax.swing.JPanel panelFondoDistribucion;
    private javax.swing.JPanel panelFondoTotal;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelResumenGeneral;
    private javax.swing.JScrollPane scrollPaneCuentasSeparadas;
    private javax.swing.JScrollPane scrollPaneDistribucionDeProductos;
    // End of variables declaration//GEN-END:variables
}
