/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;
import model.Descuento;
/**
 *
 * @author eidan
 */
public class PanelCuentaSeparadas extends javax.swing.JPanel {

    /**
     * Creates new form PanelCuentaSeparadas
     */
    public PanelCuentaSeparadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondo = new javax.swing.JPanel();
        lblIconoPersona = new javax.swing.JLabel();
        lblPersonaNumero = new javax.swing.JLabel();
        cedulaDigitada = new javax.swing.JTextField();
        lblTextoTotalAPagar = new javax.swing.JLabel();
        lblTotalAPagar = new javax.swing.JLabel();
        lblTextoDescuento = new javax.swing.JLabel();
        lblTextoIVA = new javax.swing.JLabel();
        lblSubtotalMasIVA = new javax.swing.JLabel();
        lblTextoSubtotal = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        panelListaDeProductosEnFactura = new javax.swing.JPanel();
        cBoxDescuentos = new javax.swing.JComboBox<>();

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        lblIconoPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgPersonaIcon.png"))); // NOI18N

        lblPersonaNumero.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblPersonaNumero.setForeground(new java.awt.Color(0, 0, 0));
        lblPersonaNumero.setText("Persona 1");

        cedulaDigitada.setBackground(new java.awt.Color(204, 204, 204));
        cedulaDigitada.setForeground(new java.awt.Color(102, 102, 102));
        cedulaDigitada.setText("Cedula (Opcional)");

        lblTextoTotalAPagar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblTextoTotalAPagar.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoTotalAPagar.setText("Total a pagar:");

        lblTotalAPagar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotalAPagar.setForeground(new java.awt.Color(0, 0, 0));
        lblTotalAPagar.setText("₡5650");

        lblTextoDescuento.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoDescuento.setText("Descuento % :");

        lblTextoIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoIVA.setText("IVA (13%) :");

        lblSubtotalMasIVA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotalMasIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotalMasIVA.setText("₡650");

        lblTextoSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoSubtotal.setText("Subtotal:");

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSubtotal.setForeground(new java.awt.Color(0, 0, 0));
        lblSubtotal.setText("₡5650");

        panelListaDeProductosEnFactura.setLayout(new javax.swing.BoxLayout(panelListaDeProductosEnFactura, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPersonaNumero))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cedulaDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createSequentialGroup()
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextoTotalAPagar)
                                    .addComponent(lblTextoIVA)
                                    .addComponent(lblTextoDescuento)
                                    .addComponent(lblTextoSubtotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblTotalAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                                            .addComponent(lblSubtotalMasIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(cBoxDescuentos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(12, 12, 12)))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addComponent(panelListaDeProductosEnFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIconoPersona))
                    .addGroup(panelFondoLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblPersonaNumero)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cedulaDigitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelListaDeProductosEnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoSubtotal)
                    .addComponent(lblSubtotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoDescuento)
                    .addComponent(cBoxDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoIVA)
                    .addComponent(lblSubtotalMasIVA))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTextoTotalAPagar)
                    .addComponent(lblTotalAPagar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Descuento> cBoxDescuentos;
    private javax.swing.JTextField cedulaDigitada;
    private javax.swing.JLabel lblIconoPersona;
    private javax.swing.JLabel lblPersonaNumero;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblSubtotalMasIVA;
    private javax.swing.JLabel lblTextoDescuento;
    private javax.swing.JLabel lblTextoIVA;
    private javax.swing.JLabel lblTextoSubtotal;
    private javax.swing.JLabel lblTextoTotalAPagar;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelListaDeProductosEnFactura;
    // End of variables declaration//GEN-END:variables
}
