/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.JButton;

/**
 *
 * @author eidan
 */
public class PanelPadNumerico extends javax.swing.JPanel {

    private PadListener listener;

    /**
     * Creates new form PanelPadNumerico
     */
    public PanelPadNumerico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFondoTotal = new javax.swing.JPanel();
        panelEntradaDigitar = new javax.swing.JPanel();
        btnIr = new javax.swing.JButton();
        entradaCodigoDigitado = new javax.swing.JTextField();
        LabelRegresar = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        panelFondoPadNumerico = new javax.swing.JPanel();
        btnNumero1 = new javax.swing.JButton();
        btnNumero2 = new javax.swing.JButton();
        btnNumero3 = new javax.swing.JButton();
        btnNumero4 = new javax.swing.JButton();
        btnNumero5 = new javax.swing.JButton();
        btnNumero6 = new javax.swing.JButton();
        btnNumero7 = new javax.swing.JButton();
        btnNumero8 = new javax.swing.JButton();
        btnNumero9 = new javax.swing.JButton();
        btnNumero0 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        labelFondoImagen = new javax.swing.JLabel();

        panelFondoTotal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEntradaDigitar.setBackground(new java.awt.Color(255, 255, 255));
        panelEntradaDigitar.setForeground(new java.awt.Color(0, 0, 0));

        btnIr.setBackground(new java.awt.Color(102, 255, 102));
        btnIr.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnIr.setForeground(new java.awt.Color(0, 0, 0));
        btnIr.setText("Ir");
        btnIr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrActionPerformed(evt);
            }
        });

        entradaCodigoDigitado.setBackground(new java.awt.Color(255, 255, 255));
        entradaCodigoDigitado.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        entradaCodigoDigitado.setForeground(new java.awt.Color(0, 0, 0));
        entradaCodigoDigitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaCodigoDigitadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEntradaDigitarLayout = new javax.swing.GroupLayout(panelEntradaDigitar);
        panelEntradaDigitar.setLayout(panelEntradaDigitarLayout);
        panelEntradaDigitarLayout.setHorizontalGroup(
            panelEntradaDigitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEntradaDigitarLayout.createSequentialGroup()
                .addComponent(entradaCodigoDigitado, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIr, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelEntradaDigitarLayout.setVerticalGroup(
            panelEntradaDigitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEntradaDigitarLayout.createSequentialGroup()
                .addGroup(panelEntradaDigitarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIr, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(entradaCodigoDigitado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelFondoTotal.add(panelEntradaDigitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 62, 837, 73));

        LabelRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icoRegresar.png"))); // NOI18N
        panelFondoTotal.add(LabelRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 16, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.setAlignmentX(90.0F);
        btnRegresar.setAlignmentY(50.0F);
        btnRegresar.setPreferredSize(new java.awt.Dimension(186, 42));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        panelFondoTotal.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 186, -1));

        panelFondoPadNumerico.setBackground(new java.awt.Color(255, 255, 255));
        panelFondoPadNumerico.setForeground(new java.awt.Color(255, 255, 255));

        btnNumero1.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero1.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero1.setText("1");
        btnNumero1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero1ActionPerformed(evt);
            }
        });

        btnNumero2.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero2.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero2.setText("2");
        btnNumero2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero2ActionPerformed(evt);
            }
        });

        btnNumero3.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero3.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero3.setText("3");
        btnNumero3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero3ActionPerformed(evt);
            }
        });

        btnNumero4.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero4.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero4.setText("4");
        btnNumero4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero4ActionPerformed(evt);
            }
        });

        btnNumero5.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero5.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero5.setText("5");
        btnNumero5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero5ActionPerformed(evt);
            }
        });

        btnNumero6.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero6.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero6.setText("6");
        btnNumero6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero6ActionPerformed(evt);
            }
        });

        btnNumero7.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero7.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero7.setText("7");
        btnNumero7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero7ActionPerformed(evt);
            }
        });

        btnNumero8.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero8.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero8.setText("8");
        btnNumero8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero8ActionPerformed(evt);
            }
        });

        btnNumero9.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero9.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero9.setText("9");
        btnNumero9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero9ActionPerformed(evt);
            }
        });

        btnNumero0.setBackground(new java.awt.Color(255, 255, 255));
        btnNumero0.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnNumero0.setForeground(new java.awt.Color(0, 0, 0));
        btnNumero0.setText("0");
        btnNumero0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnNumero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumero0ActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 51, 51));
        btnClear.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("C");
        btnClear.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFondoPadNumericoLayout = new javax.swing.GroupLayout(panelFondoPadNumerico);
        panelFondoPadNumerico.setLayout(panelFondoPadNumericoLayout);
        panelFondoPadNumericoLayout.setHorizontalGroup(
            panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoPadNumericoLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNumero4, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addComponent(btnNumero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNumero7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFondoPadNumericoLayout.createSequentialGroup()
                        .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNumero5, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                            .addComponent(btnNumero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNumero8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNumero3, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                            .addComponent(btnNumero6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNumero9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnNumero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        panelFondoPadNumericoLayout.setVerticalGroup(
            panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoPadNumericoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNumero9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoPadNumericoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNumero0, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelFondoTotal.add(panelFondoPadNumerico, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 143, 837, 587));

        labelFondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        panelFondoTotal.add(labelFondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondoTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrActionPerformed
        // TODO add your handling code here:
        if (listener != null) {
            listener.onAceptar(entradaCodigoDigitado.getText());
        }

    }//GEN-LAST:event_btnIrActionPerformed

    private void btnNumero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero1ActionPerformed
        // TODO add your handling code here:
        agregarNumero("1");
    }//GEN-LAST:event_btnNumero1ActionPerformed

    private void btnNumero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero2ActionPerformed
        // TODO add your handling code here:
        agregarNumero("2");
    }//GEN-LAST:event_btnNumero2ActionPerformed

    private void btnNumero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero3ActionPerformed
        // TODO add your handling code here:
        agregarNumero("3");
    }//GEN-LAST:event_btnNumero3ActionPerformed

    private void btnNumero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero4ActionPerformed
        // TODO add your handling code here:
        agregarNumero("4");
    }//GEN-LAST:event_btnNumero4ActionPerformed

    private void btnNumero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero5ActionPerformed
        // TODO add your handling code here:
        agregarNumero("5");
    }//GEN-LAST:event_btnNumero5ActionPerformed

    private void btnNumero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero6ActionPerformed
        // TODO add your handling code here:
        agregarNumero("6");
    }//GEN-LAST:event_btnNumero6ActionPerformed

    private void btnNumero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero7ActionPerformed
        // TODO add your handling code here:
        agregarNumero("7");
    }//GEN-LAST:event_btnNumero7ActionPerformed

    private void btnNumero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero8ActionPerformed
        // TODO add your handling code here:
        agregarNumero("8");
    }//GEN-LAST:event_btnNumero8ActionPerformed

    private void btnNumero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero9ActionPerformed
        // TODO add your handling code here:
        agregarNumero("9");
    }//GEN-LAST:event_btnNumero9ActionPerformed

    private void btnNumero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumero0ActionPerformed
        // TODO add your handling code here:
        agregarNumero("0");
    }//GEN-LAST:event_btnNumero0ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        entradaCodigoDigitado.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void entradaCodigoDigitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaCodigoDigitadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaCodigoDigitadoActionPerformed

    public JButton getBtnIr() {
        return btnIr;
    }

    public String getCodigo() {
        return entradaCodigoDigitado.getText();
    }

    public interface PadListener {

        void onAceptar(String valor);

        void onCancelar();
    }

    public void setPadListener(PadListener listener) {
        this.listener = listener;
    }

    private void agregarNumero(String numero) {
        entradaCodigoDigitado.setText(
                entradaCodigoDigitado.getText() + numero
        );
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelRegresar;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnIr;
    private javax.swing.JButton btnNumero0;
    private javax.swing.JButton btnNumero1;
    private javax.swing.JButton btnNumero2;
    private javax.swing.JButton btnNumero3;
    private javax.swing.JButton btnNumero4;
    private javax.swing.JButton btnNumero5;
    private javax.swing.JButton btnNumero6;
    private javax.swing.JButton btnNumero7;
    private javax.swing.JButton btnNumero8;
    private javax.swing.JButton btnNumero9;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField entradaCodigoDigitado;
    private javax.swing.JLabel labelFondoImagen;
    private javax.swing.JPanel panelEntradaDigitar;
    private javax.swing.JPanel panelFondoPadNumerico;
    private javax.swing.JPanel panelFondoTotal;
    // End of variables declaration//GEN-END:variables
}
