/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author eidan
 */
public class PanelFactura extends javax.swing.JPanel {

    /**
     * Creates new form PanelFactura
     */
    public PanelFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAbsolute = new javax.swing.JPanel();
        panelFondoAzulOscuro = new javax.swing.JPanel();
        lblTextFacturaHeader = new javax.swing.JLabel();
        btnProcederPago = new javax.swing.JButton();
        btnVolverFactura = new javax.swing.JButton();
        panelFondoBlancoFactura = new javax.swing.JPanel();
        lblTextCafeteriaGranDia = new javax.swing.JLabel();
        lblTextoFactura = new javax.swing.JLabel();
        lblNumeroFactura = new javax.swing.JLabel();
        lblHoraFactura = new javax.swing.JLabel();
        scrollPaneFactura = new javax.swing.JScrollPane();
        tableFactura = new javax.swing.JTable();
        lblTextSubTotal = new javax.swing.JLabel();
        lblTextIVA = new javax.swing.JLabel();
        descuentoComboBox = new javax.swing.JComboBox<>();
        lblTextTotal = new javax.swing.JLabel();
        lblTextPrecioSubTotal = new javax.swing.JLabel();
        lblTextIVAPrecio = new javax.swing.JLabel();
        lblTextPrecioTotal = new javax.swing.JLabel();
        lblFondoImg = new javax.swing.JLabel();

        panelAbsolute.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelFondoAzulOscuro.setBackground(new java.awt.Color(31, 42, 56));

        lblTextFacturaHeader.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextFacturaHeader.setText("Factura");

        btnProcederPago.setBackground(new java.awt.Color(51, 204, 0));
        btnProcederPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProcederPago.setForeground(new java.awt.Color(0, 0, 0));
        btnProcederPago.setText("Proceder al Pago");

        btnVolverFactura.setBackground(new java.awt.Color(255, 255, 255));
        btnVolverFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVolverFactura.setForeground(new java.awt.Color(0, 0, 0));
        btnVolverFactura.setText("Volver");

        javax.swing.GroupLayout panelFondoAzulOscuroLayout = new javax.swing.GroupLayout(panelFondoAzulOscuro);
        panelFondoAzulOscuro.setLayout(panelFondoAzulOscuroLayout);
        panelFondoAzulOscuroLayout.setHorizontalGroup(
            panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoAzulOscuroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTextFacturaHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 538, Short.MAX_VALUE)
                .addComponent(btnProcederPago, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolverFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFondoAzulOscuroLayout.setVerticalGroup(
            panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoAzulOscuroLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelFondoAzulOscuroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextFacturaHeader)
                    .addComponent(btnProcederPago, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolverFactura))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelAbsolute.add(panelFondoAzulOscuro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 80));

        panelFondoBlancoFactura.setBackground(new java.awt.Color(255, 255, 255));

        lblTextCafeteriaGranDia.setBackground(new java.awt.Color(255, 255, 255));
        lblTextCafeteriaGranDia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextCafeteriaGranDia.setForeground(new java.awt.Color(0, 0, 0));
        lblTextCafeteriaGranDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTextCafeteriaGranDia.setText("Cafetería Gran Día");

        lblTextoFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblTextoFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextoFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblTextoFactura.setText("Factura:");

        lblNumeroFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblNumeroFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumeroFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblNumeroFactura.setText("#00000");

        lblHoraFactura.setBackground(new java.awt.Color(255, 255, 255));
        lblHoraFactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblHoraFactura.setForeground(new java.awt.Color(0, 0, 0));
        lblHoraFactura.setText("2/20/2026, 2:10 a.m");

        tableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        scrollPaneFactura.setViewportView(tableFactura);

        lblTextSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextSubTotal.setText("SubTotal:");

        lblTextIVA.setBackground(new java.awt.Color(255, 255, 255));
        lblTextIVA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextIVA.setForeground(new java.awt.Color(0, 0, 0));
        lblTextIVA.setText("IVA:");

        descuentoComboBox.setBackground(new java.awt.Color(204, 204, 204));
        descuentoComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descuentoComboBox.setForeground(new java.awt.Color(0, 0, 0));
        descuentoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblTextTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextTotal.setText("Total:");

        lblTextPrecioSubTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextPrecioSubTotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextPrecioSubTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextPrecioSubTotal.setText("₡5,000");

        lblTextIVAPrecio.setBackground(new java.awt.Color(255, 255, 255));
        lblTextIVAPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTextIVAPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lblTextIVAPrecio.setText("₡650");

        lblTextPrecioTotal.setBackground(new java.awt.Color(255, 255, 255));
        lblTextPrecioTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTextPrecioTotal.setForeground(new java.awt.Color(0, 0, 0));
        lblTextPrecioTotal.setText("₡5,650");

        javax.swing.GroupLayout panelFondoBlancoFacturaLayout = new javax.swing.GroupLayout(panelFondoBlancoFactura);
        panelFondoBlancoFactura.setLayout(panelFondoBlancoFacturaLayout);
        panelFondoBlancoFacturaLayout.setHorizontalGroup(
            panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollPaneFactura))
                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(lblTextoFactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumeroFactura)
                        .addGap(112, 112, 112))
                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextIVA)
                                    .addComponent(lblTextSubTotal)
                                    .addComponent(lblTextTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 619, Short.MAX_VALUE)
                                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTextPrecioTotal)
                                    .addComponent(lblTextPrecioSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTextIVAPrecio)))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descuentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(40, 40, 40))
                    .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                        .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(326, 326, 326)
                                .addComponent(lblTextCafeteriaGranDia))
                            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                                .addGap(335, 335, 335)
                                .addComponent(lblHoraFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 344, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelFondoBlancoFacturaLayout.setVerticalGroup(
            panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoBlancoFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTextCafeteriaGranDia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoFactura)
                    .addComponent(lblNumeroFactura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHoraFactura)
                .addGap(37, 37, 37)
                .addComponent(scrollPaneFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextSubTotal)
                    .addComponent(lblTextPrecioSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextIVA)
                    .addComponent(lblTextIVAPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(descuentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelFondoBlancoFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextTotal)
                    .addComponent(lblTextPrecioTotal))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelAbsolute.add(panelFondoBlancoFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 870, 650));

        lblFondoImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        panelAbsolute.add(lblFondoImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAbsolute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcederPago;
    private javax.swing.JButton btnVolverFactura;
    private javax.swing.JComboBox<String> descuentoComboBox;
    private javax.swing.JLabel lblFondoImg;
    private javax.swing.JLabel lblHoraFactura;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblTextCafeteriaGranDia;
    private javax.swing.JLabel lblTextFacturaHeader;
    private javax.swing.JLabel lblTextIVA;
    private javax.swing.JLabel lblTextIVAPrecio;
    private javax.swing.JLabel lblTextPrecioSubTotal;
    private javax.swing.JLabel lblTextPrecioTotal;
    private javax.swing.JLabel lblTextSubTotal;
    private javax.swing.JLabel lblTextTotal;
    private javax.swing.JLabel lblTextoFactura;
    private javax.swing.JPanel panelAbsolute;
    private javax.swing.JPanel panelFondoAzulOscuro;
    private javax.swing.JPanel panelFondoBlancoFactura;
    private javax.swing.JScrollPane scrollPaneFactura;
    private javax.swing.JTable tableFactura;
    // End of variables declaration//GEN-END:variables
}
