/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author OniRuls
 */
public class ReportesAndEstatidisticas extends javax.swing.JPanel {

    /**
     * Creates new form ReportesAndEstatidisticas
     */
    public ReportesAndEstatidisticas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAzulHeader = new javax.swing.JPanel();
        reportesEstadisticasLblText = new javax.swing.JLabel();
        btnRegresarReportesNdEstadisticasPanel = new javax.swing.JButton();
        panelBlancoReportesEstadisticas = new javax.swing.JPanel();
        panelVentasDelDia = new javax.swing.JPanel();
        imgVentasDelDiaLabel = new javax.swing.JLabel();
        ventasDelDiaLblText = new javax.swing.JLabel();
        IconoColonVentasDia = new javax.swing.JLabel();
        panelVentasDelMes = new javax.swing.JPanel();
        imgVentasDelMesIcono = new javax.swing.JLabel();
        iconoColonVentasMes = new javax.swing.JLabel();
        imgVentasDelMesLabel1 = new javax.swing.JLabel();
        panelProductoMasVendido = new javax.swing.JPanel();
        imgProductoMasVendido = new javax.swing.JLabel();
        iconoProductoMasVendido = new javax.swing.JLabel();
        iconoColonProductoMasVendido = new javax.swing.JLabel();
        panelVerHistorialCompleto = new javax.swing.JPanel();
        verHistorialCompletoIcono = new javax.swing.JLabel();
        btnVerHistorialCompleto = new javax.swing.JButton();
        panelImprimirReporte = new javax.swing.JPanel();
        imprimirReporteIcono = new javax.swing.JLabel();
        btnImprimirReporte = new javax.swing.JButton();
        mainPanelReportesEstadistica = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAzulHeader.setBackground(new java.awt.Color(31, 42, 56));
        panelAzulHeader.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        reportesEstadisticasLblText.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        reportesEstadisticasLblText.setText("Reportes y Estadísticas");

        btnRegresarReportesNdEstadisticasPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresarReportesNdEstadisticasPanel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresarReportesNdEstadisticasPanel.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarReportesNdEstadisticasPanel.setText("Regresar");

        javax.swing.GroupLayout panelAzulHeaderLayout = new javax.swing.GroupLayout(panelAzulHeader);
        panelAzulHeader.setLayout(panelAzulHeaderLayout);
        panelAzulHeaderLayout.setHorizontalGroup(
            panelAzulHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reportesEstadisticasLblText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 665, Short.MAX_VALUE)
                .addComponent(btnRegresarReportesNdEstadisticasPanel)
                .addGap(15, 15, 15))
        );
        panelAzulHeaderLayout.setVerticalGroup(
            panelAzulHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAzulHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAzulHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reportesEstadisticasLblText)
                    .addComponent(btnRegresarReportesNdEstadisticasPanel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelAzulHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 50));

        panelBlancoReportesEstadisticas.setBackground(new java.awt.Color(255, 255, 255));
        panelBlancoReportesEstadisticas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelVentasDelDia.setBackground(new java.awt.Color(153, 204, 255));
        panelVentasDelDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgVentasDelDiaLabel.setForeground(new java.awt.Color(0, 0, 0));
        imgVentasDelDiaLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconVentasDelDia.png"))); // NOI18N

        ventasDelDiaLblText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ventasDelDiaLblText.setForeground(new java.awt.Color(0, 0, 0));
        ventasDelDiaLblText.setText("Ventas del Dia");

        IconoColonVentasDia.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        IconoColonVentasDia.setForeground(new java.awt.Color(0, 0, 0));
        IconoColonVentasDia.setText("₡");

        javax.swing.GroupLayout panelVentasDelDiaLayout = new javax.swing.GroupLayout(panelVentasDelDia);
        panelVentasDelDia.setLayout(panelVentasDelDiaLayout);
        panelVentasDelDiaLayout.setHorizontalGroup(
            panelVentasDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVentasDelDiaLayout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addGroup(panelVentasDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasDelDiaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(ventasDelDiaLblText))
                    .addComponent(imgVentasDelDiaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(panelVentasDelDiaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(IconoColonVentasDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVentasDelDiaLayout.setVerticalGroup(
            panelVentasDelDiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasDelDiaLayout.createSequentialGroup()
                .addComponent(imgVentasDelDiaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ventasDelDiaLblText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IconoColonVentasDia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVentasDelMes.setBackground(new java.awt.Color(153, 204, 255));
        panelVentasDelMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgVentasDelMesIcono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imgVentasDelMesIcono.setForeground(new java.awt.Color(0, 0, 0));
        imgVentasDelMesIcono.setText("Ventas del Mes");

        iconoColonVentasMes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        iconoColonVentasMes.setForeground(new java.awt.Color(0, 0, 0));
        iconoColonVentasMes.setText("₡");

        imgVentasDelMesLabel1.setForeground(new java.awt.Color(0, 0, 0));
        imgVentasDelMesLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconVentasDelMes.png"))); // NOI18N

        javax.swing.GroupLayout panelVentasDelMesLayout = new javax.swing.GroupLayout(panelVentasDelMes);
        panelVentasDelMes.setLayout(panelVentasDelMesLayout);
        panelVentasDelMesLayout.setHorizontalGroup(
            panelVentasDelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasDelMesLayout.createSequentialGroup()
                .addGroup(panelVentasDelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelVentasDelMesLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(panelVentasDelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelVentasDelMesLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imgVentasDelMesIcono))
                            .addComponent(imgVentasDelMesLabel1)))
                    .addGroup(panelVentasDelMesLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(iconoColonVentasMes)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        panelVentasDelMesLayout.setVerticalGroup(
            panelVentasDelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentasDelMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgVentasDelMesLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgVentasDelMesIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(iconoColonVentasMes)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        panelProductoMasVendido.setBackground(new java.awt.Color(153, 204, 255));
        panelProductoMasVendido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgProductoMasVendido.setForeground(new java.awt.Color(0, 0, 0));
        imgProductoMasVendido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconProductoMasVendido.png"))); // NOI18N

        iconoProductoMasVendido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iconoProductoMasVendido.setForeground(new java.awt.Color(0, 0, 0));
        iconoProductoMasVendido.setText("Producto Más Vendido");

        iconoColonProductoMasVendido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        iconoColonProductoMasVendido.setForeground(new java.awt.Color(0, 0, 0));
        iconoColonProductoMasVendido.setText("₡");

        javax.swing.GroupLayout panelProductoMasVendidoLayout = new javax.swing.GroupLayout(panelProductoMasVendido);
        panelProductoMasVendido.setLayout(panelProductoMasVendidoLayout);
        panelProductoMasVendidoLayout.setHorizontalGroup(
            panelProductoMasVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoMasVendidoLayout.createSequentialGroup()
                .addGroup(panelProductoMasVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductoMasVendidoLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(imgProductoMasVendido))
                    .addGroup(panelProductoMasVendidoLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(iconoProductoMasVendido))
                    .addGroup(panelProductoMasVendidoLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(iconoColonProductoMasVendido)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        panelProductoMasVendidoLayout.setVerticalGroup(
            panelProductoMasVendidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductoMasVendidoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imgProductoMasVendido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iconoProductoMasVendido)
                .addGap(18, 18, 18)
                .addComponent(iconoColonProductoMasVendido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelVerHistorialCompleto.setBackground(new java.awt.Color(153, 204, 255));
        panelVerHistorialCompleto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        verHistorialCompletoIcono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        verHistorialCompletoIcono.setForeground(new java.awt.Color(0, 0, 0));
        verHistorialCompletoIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconHistory.png"))); // NOI18N

        btnVerHistorialCompleto.setBackground(new java.awt.Color(255, 255, 255));
        btnVerHistorialCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerHistorialCompleto.setForeground(new java.awt.Color(0, 0, 0));
        btnVerHistorialCompleto.setText("Ver Historial Completo");

        javax.swing.GroupLayout panelVerHistorialCompletoLayout = new javax.swing.GroupLayout(panelVerHistorialCompleto);
        panelVerHistorialCompleto.setLayout(panelVerHistorialCompletoLayout);
        panelVerHistorialCompletoLayout.setHorizontalGroup(
            panelVerHistorialCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerHistorialCompletoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(verHistorialCompletoIcono)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(panelVerHistorialCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerHistorialCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelVerHistorialCompletoLayout.setVerticalGroup(
            panelVerHistorialCompletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVerHistorialCompletoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(verHistorialCompletoIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerHistorialCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelImprimirReporte.setBackground(new java.awt.Color(153, 204, 255));
        panelImprimirReporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imprimirReporteIcono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        imprimirReporteIcono.setForeground(new java.awt.Color(0, 0, 0));
        imprimirReporteIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconImprimirReporte.png"))); // NOI18N

        btnImprimirReporte.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimirReporte.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnImprimirReporte.setForeground(new java.awt.Color(0, 0, 0));
        btnImprimirReporte.setText("Imprimir Reporte");

        javax.swing.GroupLayout panelImprimirReporteLayout = new javax.swing.GroupLayout(panelImprimirReporte);
        panelImprimirReporte.setLayout(panelImprimirReporteLayout);
        panelImprimirReporteLayout.setHorizontalGroup(
            panelImprimirReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprimirReporteLayout.createSequentialGroup()
                .addContainerGap(128, Short.MAX_VALUE)
                .addComponent(imprimirReporteIcono)
                .addGap(122, 122, 122))
            .addGroup(panelImprimirReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnImprimirReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelImprimirReporteLayout.setVerticalGroup(
            panelImprimirReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImprimirReporteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imprimirReporteIcono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimirReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelBlancoReportesEstadisticasLayout = new javax.swing.GroupLayout(panelBlancoReportesEstadisticas);
        panelBlancoReportesEstadisticas.setLayout(panelBlancoReportesEstadisticasLayout);
        panelBlancoReportesEstadisticasLayout.setHorizontalGroup(
            panelBlancoReportesEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoReportesEstadisticasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVentasDelDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(panelVentasDelMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelProductoMasVendido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(panelBlancoReportesEstadisticasLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(panelVerHistorialCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(panelImprimirReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBlancoReportesEstadisticasLayout.setVerticalGroup(
            panelBlancoReportesEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoReportesEstadisticasLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(panelBlancoReportesEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelProductoMasVendido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelVentasDelMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelVentasDelDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addGroup(panelBlancoReportesEstadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelVerHistorialCompleto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelImprimirReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(panelBlancoReportesEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 980, 660));

        mainPanelReportesEstadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        add(mainPanelReportesEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IconoColonVentasDia;
    private javax.swing.JButton btnImprimirReporte;
    private javax.swing.JButton btnRegresarReportesNdEstadisticasPanel;
    private javax.swing.JButton btnVerHistorialCompleto;
    private javax.swing.JLabel iconoColonProductoMasVendido;
    private javax.swing.JLabel iconoColonVentasMes;
    private javax.swing.JLabel iconoProductoMasVendido;
    private javax.swing.JLabel imgProductoMasVendido;
    private javax.swing.JLabel imgVentasDelDiaLabel;
    private javax.swing.JLabel imgVentasDelMesIcono;
    private javax.swing.JLabel imgVentasDelMesLabel1;
    private javax.swing.JLabel imprimirReporteIcono;
    private javax.swing.JLabel mainPanelReportesEstadistica;
    private javax.swing.JPanel panelAzulHeader;
    private javax.swing.JPanel panelBlancoReportesEstadisticas;
    private javax.swing.JPanel panelImprimirReporte;
    private javax.swing.JPanel panelProductoMasVendido;
    private javax.swing.JPanel panelVentasDelDia;
    private javax.swing.JPanel panelVentasDelMes;
    private javax.swing.JPanel panelVerHistorialCompleto;
    private javax.swing.JLabel reportesEstadisticasLblText;
    private javax.swing.JLabel ventasDelDiaLblText;
    private javax.swing.JLabel verHistorialCompletoIcono;
    // End of variables declaration//GEN-END:variables
}
