/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author OniRuls
 */
public class SeleccionPago extends javax.swing.JPanel {

    /**
     * Creates new form SeleccionPago
     */
    public SeleccionPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        panelBlancoSeleccionPago = new javax.swing.JPanel();
        panelEfectivoPago = new javax.swing.JPanel();
        iconoDinero = new javax.swing.JLabel();
        btnEfectivo = new javax.swing.JButton();
        panelTarjetaPago = new javax.swing.JPanel();
        iconoTarjeta = new javax.swing.JLabel();
        btnTarjeta = new javax.swing.JButton();
        panelPagoMixto = new javax.swing.JPanel();
        iconoPagoMixto = new javax.swing.JLabel();
        btnPagoMixto = new javax.swing.JButton();
        panelSinpeMovilPago = new javax.swing.JPanel();
        iconoSinpeMovil = new javax.swing.JLabel();
        btnSinpeMovil = new javax.swing.JButton();
        btnRegresarSeleccionPago = new javax.swing.JButton();
        imgFondoOpacoSeleccionPago = new javax.swing.JLabel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBlancoSeleccionPago.setBackground(new java.awt.Color(255, 255, 255));
        panelBlancoSeleccionPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelEfectivoPago.setBackground(new java.awt.Color(204, 255, 204));
        panelEfectivoPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iconoDinero.setForeground(new java.awt.Color(0, 0, 0));
        iconoDinero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IconMoneyBag.png"))); // NOI18N

        btnEfectivo.setBackground(new java.awt.Color(255, 255, 255));
        btnEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEfectivo.setForeground(new java.awt.Color(0, 0, 0));
        btnEfectivo.setText("Efectivo");

        javax.swing.GroupLayout panelEfectivoPagoLayout = new javax.swing.GroupLayout(panelEfectivoPago);
        panelEfectivoPago.setLayout(panelEfectivoPagoLayout);
        panelEfectivoPagoLayout.setHorizontalGroup(
            panelEfectivoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivoPagoLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(panelEfectivoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconoDinero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEfectivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panelEfectivoPagoLayout.setVerticalGroup(
            panelEfectivoPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEfectivoPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoDinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEfectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        panelTarjetaPago.setBackground(new java.awt.Color(204, 255, 204));
        panelTarjetaPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iconoTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        iconoTarjeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconCard.png"))); // NOI18N

        btnTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        btnTarjeta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        btnTarjeta.setText("Tarjeta");

        javax.swing.GroupLayout panelTarjetaPagoLayout = new javax.swing.GroupLayout(panelTarjetaPago);
        panelTarjetaPago.setLayout(panelTarjetaPagoLayout);
        panelTarjetaPagoLayout.setHorizontalGroup(
            panelTarjetaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTarjetaPagoLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(panelTarjetaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconoTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(111, 111, 111))
        );
        panelTarjetaPagoLayout.setVerticalGroup(
            panelTarjetaPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTarjetaPagoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoTarjeta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        panelPagoMixto.setBackground(new java.awt.Color(204, 255, 204));
        panelPagoMixto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iconoPagoMixto.setForeground(new java.awt.Color(0, 0, 0));
        iconoPagoMixto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconPagoMixto.png"))); // NOI18N

        btnPagoMixto.setBackground(new java.awt.Color(255, 255, 255));
        btnPagoMixto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPagoMixto.setForeground(new java.awt.Color(0, 0, 0));
        btnPagoMixto.setText("Pago Mixto");
        btnPagoMixto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagoMixtoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPagoMixtoLayout = new javax.swing.GroupLayout(panelPagoMixto);
        panelPagoMixto.setLayout(panelPagoMixtoLayout);
        panelPagoMixtoLayout.setHorizontalGroup(
            panelPagoMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoMixtoLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(panelPagoMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconoPagoMixto)
                    .addComponent(btnPagoMixto))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        panelPagoMixtoLayout.setVerticalGroup(
            panelPagoMixtoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPagoMixtoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconoPagoMixto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPagoMixto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelSinpeMovilPago.setBackground(new java.awt.Color(204, 255, 204));
        panelSinpeMovilPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        iconoSinpeMovil.setForeground(new java.awt.Color(0, 0, 0));
        iconoSinpeMovil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSinpeMovil.png"))); // NOI18N

        btnSinpeMovil.setBackground(new java.awt.Color(255, 255, 255));
        btnSinpeMovil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSinpeMovil.setForeground(new java.awt.Color(0, 0, 0));
        btnSinpeMovil.setText("Sinpe Móvil");

        javax.swing.GroupLayout panelSinpeMovilPagoLayout = new javax.swing.GroupLayout(panelSinpeMovilPago);
        panelSinpeMovilPago.setLayout(panelSinpeMovilPagoLayout);
        panelSinpeMovilPagoLayout.setHorizontalGroup(
            panelSinpeMovilPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinpeMovilPagoLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panelSinpeMovilPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iconoSinpeMovil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSinpeMovil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        panelSinpeMovilPagoLayout.setVerticalGroup(
            panelSinpeMovilPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSinpeMovilPagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconoSinpeMovil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSinpeMovil, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout panelBlancoSeleccionPagoLayout = new javax.swing.GroupLayout(panelBlancoSeleccionPago);
        panelBlancoSeleccionPago.setLayout(panelBlancoSeleccionPagoLayout);
        panelBlancoSeleccionPagoLayout.setHorizontalGroup(
            panelBlancoSeleccionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoSeleccionPagoLayout.createSequentialGroup()
                .addGroup(panelBlancoSeleccionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBlancoSeleccionPagoLayout.createSequentialGroup()
                        .addGap(564, 564, 564)
                        .addComponent(panelPagoMixto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBlancoSeleccionPagoLayout.createSequentialGroup()
                        .addGroup(panelBlancoSeleccionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBlancoSeleccionPagoLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(panelEfectivoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelBlancoSeleccionPagoLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(panelSinpeMovilPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTarjetaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        panelBlancoSeleccionPagoLayout.setVerticalGroup(
            panelBlancoSeleccionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlancoSeleccionPagoLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(panelBlancoSeleccionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEfectivoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTarjetaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(panelBlancoSeleccionPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelSinpeMovilPago, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPagoMixto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(209, 209, 209))
        );

        add(panelBlancoSeleccionPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 960, 680));

        btnRegresarSeleccionPago.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresarSeleccionPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegresarSeleccionPago.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresarSeleccionPago.setText("Regresar");
        add(btnRegresarSeleccionPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 10, -1, -1));

        imgFondoOpacoSeleccionPago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgFondoOpaco.jpeg"))); // NOI18N
        add(imgFondoOpacoSeleccionPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagoMixtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagoMixtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagoMixtoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEfectivo;
    private javax.swing.JButton btnPagoMixto;
    private javax.swing.JButton btnRegresarSeleccionPago;
    private javax.swing.JButton btnSinpeMovil;
    private javax.swing.JButton btnTarjeta;
    private javax.swing.JLabel iconoDinero;
    private javax.swing.JLabel iconoPagoMixto;
    private javax.swing.JLabel iconoSinpeMovil;
    private javax.swing.JLabel iconoTarjeta;
    private javax.swing.JLabel imgFondoOpacoSeleccionPago;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel panelBlancoSeleccionPago;
    private javax.swing.JPanel panelEfectivoPago;
    private javax.swing.JPanel panelPagoMixto;
    private javax.swing.JPanel panelSinpeMovilPago;
    private javax.swing.JPanel panelTarjetaPago;
    // End of variables declaration//GEN-END:variables
}
